In [2]:
import pandas as pd
import os
os.chdir(r'/Users/caicaiqijun/智慧牙/数据/全国数据/全国数据得分/2022/5月/标准字段/单个公司标准化字段')
pd.set_option('max_colwidth',1000)
pd.set_option('max_columns',100)
pd.set_option('max_rows',100)

# 标准化前

## looping_test_sse_company_nonpatent_indicators

In [3]:
looping_test_sse_company_nonpatent_indicators=pd.read_csv('looping_test_sse_company_nonpatent_indicators.csv')

In [4]:
looping_test_sse_company_nonpatent_indicators

,company_id,duration,actual_capital_formatted,reg_capital_formatted,ans_id,company_name,public,qualify_certificate,seic_lv1,seic_lv2,...,reg_num_5y,reg_growth_ratio,reg_3y_avg,num_trademarks_registered,num_trademarks_total,num_trademarks_registered_5y,num_trademarks_total_5y,num_certificates,num_certificates_valid,num_members
0,000FA681D1E7610073C53DA8CF8CF6A7,6.726027,0.000000e+00,3.000000e+06,ed596d9b-ea93-41e5-a5d7-522ea72bae22,绵阳数智生物科技有限公司,NaN,科技型中小企业,生物产业,生物医药产业,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,0014A83C9B038292B6E0DB202479DEB9,4.989041,0.000000e+00,1.000000e+06,NaN,苏州载道网络科技有限公司,NaN,江苏省民营科技企业,新一代信息技术产业,新兴软件和新型信息技术服务,...,53.0,-0.221501,6.666667,1.0,1.0,1.0,1.0,NaN,NaN,NaN
2,001CE08C53F7BD9A821358DD21C50C88,19.591781,3.633573e+09,3.633573e+09,NaN,中航证券有限公司,NaN,NaN,相关服务业,其他相关服务,...,1.0,-1.000000,NaN,2.0,4.0,1.0,3.0,NaN,NaN,NaN
3,0067F4DD86BE9866BD8E617D2B88E821,7.257534,0.000000e+00,7.000000e+06,5de5cd27-7cc7-4b88-b482-cf7ce5811143,重庆纳川山隅重工设备有限公司,NaN,NaN,高端装备制造产业,智能制造装备产业,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,006A322857D17795374D7749C2C32538,10.139726,2.000000e+06,2.000000e+06,e9aa448c-09db-4d69-8176-3368e8812bf7,中山市钜泰硅胶科技有限公司,NaN,科技型中小企业__高新技术企业,新材料产业,先进无机非金属材料,...,NaN,NaN,NaN,2.0,2.0,0.0,0.0,2.0,2.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1110047,C7C049CDA7F42E6D89B2D5351D6B0412,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0
1110048,C85082D305A61A9633616A87858E156B,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22.0
1110049,E586B12C6FBDBE45B224378D90FE78A8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0
1110050,F74C48AD2E7CF455975FBF6C1BC9F29C,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0
1110051,FD9510BB0B4C5092BFEB060E5B3AFD91,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0

In [6]:
looping_test_sse_company_nonpatent_indicators.columns

Index(['company_id', 'duration', 'actual_capital_formatted',
       'reg_capital_formatted', 'ans_id', 'company_name', 'public',
       'qualify_certificate', 'seic_lv1', 'seic_lv2', 'province', 'city',
       'status', 'rounds', 'money_q25_sum_weighted',
       'most_recent_money_q25_formatted', 'most_recent_time',
       'avg_funding_interval', 'reg_num', 'reg_num_5y', 'reg_growth_ratio',
       'reg_3y_avg', 'num_trademarks_registered', 'num_trademarks_total',
       'num_trademarks_registered_5y', 'num_trademarks_total_5y',
       'num_certificates', 'num_certificates_valid', 'num_members'],
      dtype='object')

###  qualify_certificate

In [265]:
qualify_certificate=looping_test_sse_company_nonpatent_indicators[['company_id','ans_id','company_name',
                                                                  'seic_lv2','qualify_certificate']]
qualify_certificate

,company_id,ans_id,company_name,seic_lv2,qualify_certificate
0,000FA681D1E7610073C53DA8CF8CF6A7,ed596d9b-ea93-41e5-a5d7-522ea72bae22,绵阳数智生物科技有限公司,生物医药产业,科技型中小企业
1,0014A83C9B038292B6E0DB202479DEB9,NaN,苏州载道网络科技有限公司,新兴软件和新型信息技术服务,江苏省民营科技企业
2,001CE08C53F7BD9A821358DD21C50C88,NaN,中航证券有限公司,其他相关服务,NaN
3,0067F4DD86BE9866BD8E617D2B88E821,5de5cd27-7cc7-4b88-b482-cf7ce5811143,重庆纳川山隅重工设备有限公司,智能制造装备产业,NaN
4,006A322857D17795374D7749C2C32538,e9aa448c-09db-4d69-8176-3368e8812bf7,中山市钜泰硅胶科技有限公司,先进无机非金属材料,科技型中小企业__高新技术企业
...,...,...,...,...,...
1110047,C7C049CDA7F42E6D89B2D5351D6B0412,NaN,NaN,NaN,NaN
1110048,C85082D305A61A9633616A87858E156B,NaN,NaN,NaN,NaN
1110049,E586B12C6FBDBE45B224378D90FE78A8,NaN,NaN,NaN,NaN
1110050,F74C48AD2E7CF455975FBF6C1BC9F29C,NaN,NaN,NaN,NaN
1110051,FD9510BB0B4C5092BFEB060E5B3AFD91,NaN,NaN,NaN,NaN

In [14]:
qualify_certificate[qualify_certificate['qualify_certificate'].notnull()]

,company_id,ans_id,company_name,seic_lv2,qualify_certificate
0,000FA681D1E7610073C53DA8CF8CF6A7,ed596d9b-ea93-41e5-a5d7-522ea72bae22,绵阳数智生物科技有限公司,生物医药产业,科技型中小企业
1,0014A83C9B038292B6E0DB202479DEB9,NaN,苏州载道网络科技有限公司,新兴软件和新型信息技术服务,江苏省民营科技企业
4,006A322857D17795374D7749C2C32538,e9aa448c-09db-4d69-8176-3368e8812bf7,中山市钜泰硅胶科技有限公司,先进无机非金属材料,科技型中小企业__高新技术企业
5,0097CB3253FA5EBCE4BB882305ACB03A,28242ee9-180e-4301-8601-5c42ed2f8f0c,马鞍山市德善金属成型科技有限公司,先进有色金属材料,高新技术企业
9,00D6CAD68E52953C9922B3AB737CEDC0,NaN,上海铱芯信息科技有限公司,新兴软件和新型信息技术服务,科技型中小企业
...,...,...,...,...,...
1109342,FF21C6D8BC758928BCC2A5B6F411318A,b72c1c50-1e41-45a1-8c07-0f8162b00fa8,上海创程车联网络科技有限公司,下一代信息网络产业,上海市专精特新__高新技术企业
1109344,FF55E3264CFCD701C92203516FE1A7D3,9b729f15-ec59-404b-849e-0fdc8b4b97c3,上海乔源智能化设备有限公司,人工智能,科技型中小企业
1109348,FFB2CCFAC37353C551D5377EEC23108F,f10f02ed-152b-4721-b6e6-5331eb5860f5,滁州岳众汽车零部件有限公司,其它,科技型中小企业__高新技术企业
1109350,FFC4CEC75FA040BC86DFABE24A94CB23,NaN,广州必望信息技术有限公司,新兴软件和新型信息技术服务,科技型中小企业__高新技术企业
1109351,FFE318C4EA741399699C17DE9C533DC7,NaN,厦门文杉信息科技有限公司,互联网与云计算、大数据服务,高新技术企业

In [266]:
qualify_certificate.query('company_id=="A70A3E493E6B6E9C3D1CDA03B6279CAA"')

,company_id,ans_id,company_name,seic_lv2,qualify_certificate
929734,A70A3E493E6B6E9C3D1CDA03B6279CAA,f039e90a-679c-4c50-ab06-72d03d496c4f,华为技术有限公司,下一代信息网络产业,高新技术企业

### num_certificates

In [33]:
num_certificates_front=looping_test_sse_company_nonpatent_indicators[['company_id','ans_id','company_name',
                                                                  'seic_lv2','num_certificates']]
num_certificates_front

,company_id,ans_id,company_name,seic_lv2,num_certificates
0,000FA681D1E7610073C53DA8CF8CF6A7,ed596d9b-ea93-41e5-a5d7-522ea72bae22,绵阳数智生物科技有限公司,生物医药产业,NaN
1,0014A83C9B038292B6E0DB202479DEB9,NaN,苏州载道网络科技有限公司,新兴软件和新型信息技术服务,NaN
2,001CE08C53F7BD9A821358DD21C50C88,NaN,中航证券有限公司,其他相关服务,NaN
3,0067F4DD86BE9866BD8E617D2B88E821,5de5cd27-7cc7-4b88-b482-cf7ce5811143,重庆纳川山隅重工设备有限公司,智能制造装备产业,NaN
4,006A322857D17795374D7749C2C32538,e9aa448c-09db-4d69-8176-3368e8812bf7,中山市钜泰硅胶科技有限公司,先进无机非金属材料,2.0
...,...,...,...,...,...
1110047,C7C049CDA7F42E6D89B2D5351D6B0412,NaN,NaN,NaN,NaN
1110048,C85082D305A61A9633616A87858E156B,NaN,NaN,NaN,NaN
1110049,E586B12C6FBDBE45B224378D90FE78A8,NaN,NaN,NaN,NaN
1110050,F74C48AD2E7CF455975FBF6C1BC9F29C,NaN,NaN,NaN,NaN
1110051,FD9510BB0B4C5092BFEB060E5B3AFD91,NaN,NaN,NaN,NaN

In [34]:
num_certificates_front[num_certificates_front['num_certificates'].notnull()]

,company_id,ans_id,company_name,seic_lv2,num_certificates
4,006A322857D17795374D7749C2C32538,e9aa448c-09db-4d69-8176-3368e8812bf7,中山市钜泰硅胶科技有限公司,先进无机非金属材料,2.0
5,0097CB3253FA5EBCE4BB882305ACB03A,28242ee9-180e-4301-8601-5c42ed2f8f0c,马鞍山市德善金属成型科技有限公司,先进有色金属材料,4.0
7,00B7A232CC0D73DFE36EE4BD25E40E05,b51be918-8175-4bfe-9b44-50647094dcae,福建美美饰股份有限公司,其它,1.0
10,00E0C127D47E8F4944B61BD0B4B8BACF,NaN,昆山恺博传动系统有限公司,智能制造装备产业,1.0
12,00FF6CBBF0320CB4961643084A2C6B0D,2fa9614b-d4a8-46de-a856-3f1f43f0cdc4,苏州运恒精冲科技有限公司,先进钢铁材料,3.0
...,...,...,...,...,...
1110014,FC9B796F3C2BA403F199A7C36FB16F00,NaN,NaN,NaN,1.0
1110015,FCF0BF7A64903D4D14CD8F25164AC0B5,NaN,NaN,NaN,1.0
1110016,FD0A215D887A77460445CDE541AB4653,NaN,NaN,NaN,2.0
1110017,FDEED7B67675594F2E6EBDDB3397EFC2,NaN,NaN,NaN,1.0
1110018,FF15DFCACF2B6956E935CE8E0142FC6B,NaN,NaN,NaN,4.0

In [36]:
num_certificates_front.query('company_id=="FFE318C4EA741399699C17DE9C533DC7"')

,company_id,ans_id,company_name,seic_lv2,num_certificates
1109351,FFE318C4EA741399699C17DE9C533DC7,NaN,厦门文杉信息科技有限公司,互联网与云计算、大数据服务,6.0

### public

In [326]:
looping_test_sse_company_nonpatent_indicators[looping_test_sse_company_nonpatent_indicators['public'].notnull()]

,company_id,duration,actual_capital_formatted,reg_capital_formatted,ans_id,company_name,public,qualify_certificate,seic_lv1,seic_lv2,province,city,status,rounds,money_q25_sum_weighted,most_recent_money_q25_formatted,most_recent_time,avg_funding_interval,reg_num,reg_num_5y,reg_growth_ratio,reg_3y_avg,num_trademarks_registered,num_trademarks_total,num_trademarks_registered_5y,num_trademarks_total_5y,num_certificates,num_certificates_valid,num_members
204,12FDB87639C672562BC16014B5E37D45,24.789041,30030000.0,3.003000e+07,a406f2cd-dfa4-42b1-b931-c1dceb09f9a2,安徽省志成建设工程咨询股份有限公司,新三板,科技型中小企业__高新技术企业,相关服务业,新技术与创新创业服务,安徽省,合肥市,ACTIVE,NaN,NaN,NaN,NaN,NaN,14.0,14.0,1.000000,4.666667,5.0,5.0,0.0,0.0,8.0,8.0,10.0
212,13A6F11185EE00CA9BDA55A78A81029C,21.526027,120000000.0,1.862851e+09,0ce820ce-508a-4d64-8a8f-ba3daf995d0e,航天信息股份有限公司,A股,高新技术企业,新一代信息技术产业,新兴软件和新型信息技术服务,北京市,北京市,ACTIVE,NaN,NaN,NaN,NaN,NaN,898.0,532.0,-0.104610,93.000000,149.0,164.0,28.0,41.0,124.0,94.0,26.0
318,1AFAC5D791C1F547C8E955A768620FA0,21.046575,22110000.0,3.777600e+07,c662d401-fa95-45b4-bdf3-ca0d7e8c2e9b,山东汉鑫科技股份有限公司,新三板,高新技术企业__瞪羚企业,新一代信息技术产业,人工智能,山东省,烟台市,ACTIVE,NaN,NaN,NaN,NaN,NaN,56.0,35.0,0.643168,9.000000,14.0,14.0,10.0,10.0,9.0,9.0,10.0
396,217821701C22450438C955B27908AE1B,14.109589,257545400.0,2.575454e+08,7afba3db-6f7a-4a7c-a13f-554c46665b8e,万凯新材料股份有限公司,A股,高新技术企业,新材料产业,先进石化化工新材料,浙江省,嘉兴市,ACTIVE,4.0,20837875.0,10000000.0,2.449315,0.190868,NaN,NaN,NaN,NaN,1.0,1.0,0.0,0.0,8.0,8.0,2.0
455,2794EFA83AACEEBDD8E9108349082384,16.482192,21135000.0,2.450000e+07,9c3f25a6-20f9-4afb-b991-9cfbf17f89dd,上海双申医疗器械股份有限公司,新三板,科技型中小企业__高新技术企业,生物产业,生物医学工程产业,上海市,上海市,ACTIVE,2.0,16550375.0,66201500.0,6.739726,0.517808,19.0,12.0,-0.118083,2.333333,6.0,6.0,1.0,1.0,14.0,14.0,13.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1109011,E058AD3082A483A2C6EEEAB08B9AF45B,11.194521,5100000.0,1.527000e+07,NaN,上海上亿传媒股份有限公司,新三板,NaN,新一代信息技术产业,互联网与云计算、大数据服务,上海市,上海市,ACTIVE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,16.0,0.0,12.0,NaN,NaN,9.0
1109057,E49C50CBD520D17F2CA59CEEF2066758,15.501370,20000000.0,2.000000e+07,NaN,上海信易信息科技股份有限公司,新三板,科技型中小企业__高新技术企业,新一代信息技术产业,新兴软件和新型信息技术服务,上海市,上海市,ACTIVE,NaN,NaN,NaN,NaN,NaN,35.0,28.0,0.032796,5.333333,8.0,12.0,1.0,5.0,2.0,2.0,9.0
1109095,E800AD3A38A536C7915266BFCCE48AF2,15.183562,35000000.0,3.500000e+07,2ece4e92-22d1-4564-bb26-debf6aad96c8,东莞市鑫聚光电科技股份有限公司,新三板,高新技术企业,新一代信息技术产业,电子核心产业,广东省,东莞市,ACTIVE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,35.0,40.0,28.0,32.0,1.0,1.0,13.0
1109169,EE955F86069DC67F4F8C7695CB1734B4,20.663014,10000000.0,1.000000e+07,NaN,江苏创元数码股份有限公司,新三板,NaN,数字创意产业,数字创意技术设备制造,江苏省,苏州市,ACTIVE,2.0,3730000.0,10000000.0,3.224658,0.306849,NaN,NaN,NaN,NaN,4.0,23.0,3.0,22.0,NaN,NaN,NaN
1109340,FEF7ECB78AE80ED75E3914E675A7421B,19.939726,44987000.0,6.748050e+07,e0079705-0d66-42e0-bf8b-f32d297e3208,成都畅达通检测技术股份有限公司,新三板,科技型中小企业__高新技术企业,相关服务业,新技术与创新创业服务,四川省,成都市,ACTIVE,NaN,NaN,NaN,NaN,NaN,9.0,2.0,-1.000000,NaN,4.0,4.0,0.0,0.0,2.0,2.0,11.0

# 标准化后

## looping_test_feature_switch_sse_company_nonpatent_indicators

In [3]:
looping_test_feature_switch_sse_company_nonpatent_indicators=pd.read_csv('looping_test_feature_switch_20220509_sse_company_nonpatent_indicators.csv')
looping_test_feature_switch_sse_company_nonpatent_indicators

,company_id,duration,actual_capital_formatted,reg_capital_formatted,qualify_certificate,ans_id,company_name,seic_lv1,seic_lv2,province,city,status,public,rounds,money_q25_sum_weighted,most_recent_money_q25_formatted,most_recent_time,avg_funding_interval,reg_num,reg_num_5y,reg_growth_ratio,reg_3y_avg,num_trademarks_registered,num_trademarks_total,num_trademarks_registered_5y,num_trademarks_total_5y,num_certificates,num_certificates_valid,num_members
0,000FA681D1E7610073C53DA8CF8CF6A7,6.734247,0.000000e+00,3.000000e+06,科技型中小企业,ed596d9b-ea93-41e5-a5d7-522ea72bae22,绵阳数智生物科技有限公司,生物产业,生物医药产业,四川省,绵阳市,ACTIVE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,0014A83C9B038292B6E0DB202479DEB9,4.997260,0.000000e+00,1.000000e+06,NaN,NaN,苏州载道网络科技有限公司,新一代信息技术产业,新兴软件和新型信息技术服务,江苏省,苏州市,ACTIVE,NaN,NaN,NaN,NaN,NaN,NaN,53.0,53.0,-0.221501,6.666667,1.0,1.0,1.0,1.0,NaN,NaN,NaN
2,001CE08C53F7BD9A821358DD21C50C88,19.600000,3.633573e+09,3.633573e+09,NaN,NaN,中航证券有限公司,相关服务业,其他相关服务,江西省,南昌市,ACTIVE,NaN,1.0,8275187.5,66201500.0,6.473973,NaN,1.0,1.0,-1.000000,NaN,2.0,4.0,1.0,3.0,NaN,NaN,NaN
3,0067F4DD86BE9866BD8E617D2B88E821,7.265753,0.000000e+00,7.000000e+06,NaN,5de5cd27-7cc7-4b88-b482-cf7ce5811143,重庆纳川山隅重工设备有限公司,高端装备制造产业,智能制造装备产业,重庆市,重庆市,ACTIVE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,006A322857D17795374D7749C2C32538,10.147945,2.000000e+06,2.000000e+06,高新技术企业__科技型中小企业,e9aa448c-09db-4d69-8176-3368e8812bf7,中山市钜泰硅胶科技有限公司,新材料产业,先进无机非金属材料,广东省,中山市,ACTIVE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2.0,0.0,0.0,2.0,2.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1109774,C7C049CDA7F42E6D89B2D5351D6B0412,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0
1109775,C85082D305A61A9633616A87858E156B,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22.0
1109776,E586B12C6FBDBE45B224378D90FE78A8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0
1109777,F74C48AD2E7CF455975FBF6C1BC9F29C,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0
1109778,FD9510BB0B4C5092BFEB060E5B3AFD91,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0

In [51]:
looping_test_feature_switch_sse_company_nonpatent_indicators.columns

Index(['company_id', 'duration', 'actual_capital_formatted',
       'reg_capital_formatted', 'qualify_certificate', 'ans_id',
       'company_name', 'seic_lv1', 'seic_lv2', 'province', 'city', 'status',
       'public', 'rounds', 'money_q25_sum_weighted',
       'most_recent_money_q25_formatted', 'most_recent_time',
       'avg_funding_interval', 'reg_num', 'reg_num_5y', 'reg_growth_ratio',
       'reg_3y_avg', 'num_trademarks_registered', 'num_trademarks_total',
       'num_trademarks_registered_5y', 'num_trademarks_total_5y',
       'num_certificates', 'num_certificates_valid', 'num_members'],
      dtype='object')

In [41]:
certificates=looping_test_feature_switch_sse_company_nonpatent_indicators[['company_id','company_name','num_certificates','num_certificates_valid']]
certificates

,company_id,company_name,num_certificates,num_certificates_valid
0,000FA681D1E7610073C53DA8CF8CF6A7,绵阳数智生物科技有限公司,NaN,NaN
1,0014A83C9B038292B6E0DB202479DEB9,苏州载道网络科技有限公司,NaN,NaN
2,001CE08C53F7BD9A821358DD21C50C88,中航证券有限公司,NaN,NaN
3,0067F4DD86BE9866BD8E617D2B88E821,重庆纳川山隅重工设备有限公司,NaN,NaN
4,006A322857D17795374D7749C2C32538,中山市钜泰硅胶科技有限公司,2.0,2.0
...,...,...,...,...
1109774,C7C049CDA7F42E6D89B2D5351D6B0412,NaN,NaN,NaN
1109775,C85082D305A61A9633616A87858E156B,NaN,NaN,NaN
1109776,E586B12C6FBDBE45B224378D90FE78A8,NaN,NaN,NaN
1109777,F74C48AD2E7CF455975FBF6C1BC9F29C,NaN,NaN,NaN
1109778,FD9510BB0B4C5092BFEB060E5B3AFD91,NaN,NaN,NaN

In [42]:
certificates.fillna(0,inplace=True)

/Users/caicaiqijun/opt/anaconda3/lib/python3.7/site-packages/pandas/core/frame.py:5182: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  downcast=downcast,

In [43]:
import numpy as np

In [44]:
certificates['change']=np.where(certificates['num_certificates']==certificates['num_certificates_valid'],1,0)

/Users/caicaiqijun/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [45]:
certificates['change'].value_counts()

1    1014151
0      95628
Name: change, dtype: int64

In [46]:
certificates['gap']=abs(certificates['num_certificates']-certificates['num_certificates_valid'])
certificates

/Users/caicaiqijun/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

,company_id,company_name,num_certificates,num_certificates_valid,change,gap
0,000FA681D1E7610073C53DA8CF8CF6A7,绵阳数智生物科技有限公司,0.0,0.0,1,0.0
1,0014A83C9B038292B6E0DB202479DEB9,苏州载道网络科技有限公司,0.0,0.0,1,0.0
2,001CE08C53F7BD9A821358DD21C50C88,中航证券有限公司,0.0,0.0,1,0.0
3,0067F4DD86BE9866BD8E617D2B88E821,重庆纳川山隅重工设备有限公司,0.0,0.0,1,0.0
4,006A322857D17795374D7749C2C32538,中山市钜泰硅胶科技有限公司,2.0,2.0,1,0.0
...,...,...,...,...,...,...
1109774,C7C049CDA7F42E6D89B2D5351D6B0412,0,0.0,0.0,1,0.0
1109775,C85082D305A61A9633616A87858E156B,0,0.0,0.0,1,0.0
1109776,E586B12C6FBDBE45B224378D90FE78A8,0,0.0,0.0,1,0.0
1109777,F74C48AD2E7CF455975FBF6C1BC9F29C,0,0.0,0.0,1,0.0
1109778,FD9510BB0B4C5092BFEB060E5B3AFD91,0,0.0,0.0,1,0.0

In [48]:
certificates.query('num_certificates>10 and num_certificates_valid<1.5').head(100)

,company_id,company_name,num_certificates,num_certificates_valid,change,gap
11419,F534051B1A92F28B269A9C2AF8D1C18D,深圳市李森科技有限公司,15.0,1.0,0,14.0
18368,609C31A0C937BFA7F9A0DF90245443C3,深圳市荣通盛凯科技有限公司,12.0,0.0,0,12.0
20357,12F04A367EEACCFD334BEDF49D32BD54,喜德瑞采暖设备（上海）有限公司,17.0,0.0,0,17.0
25807,FC24FEC90B109CC79AE85C2C766D3D47,苏州信伟电器有限公司,15.0,0.0,0,15.0
27177,73248993A1EE9D7A624D5BF46F436765,湖北万众体育产业有限公司,19.0,1.0,0,18.0
34168,EA33E02C392F6FC214C125ED39CF02E4,无锡市金超威新能源科技有限公司,13.0,0.0,0,13.0
37866,36D9EE3AC595DA4CD2A9C50B28064665,广东智高文化创意股份有限公司,11.0,0.0,0,11.0
40560,2A5E46A46FDCE1A56111667CC66B534D,中电科声光电科技股份有限公司,14.0,1.0,0,13.0
53763,CDB6B2DFC5702F407C40555238F74028,深圳建扬技术有限公司,11.0,1.0,0,10.0
54354,015FEAE70735DA91E0D78CF161DA1C2E,广东老万格洛尼热能科技有限公司,17.0,1.0,0,16.0
60691,371C04D258B695F9F94AB64048650001,东莞市戴盛电源技术股份有限公司,18.0,0.0,0,18.0
72301,5786D4F2267C791B71420509303A74A5,主力智业（深圳）电器实业有限公司,11.0,0.0,0,11.0
82701,033B8FFAEE71F7E634B34F6C1848020C,中山市臻隆婴童用品有限公司,12.0,1.0,0,11.0
86677,69926DC90D9706B4231311F5CBDB30A8,福建新福达汽车工业有限公司,34.0,1.0,0,33.0
95207,714C27BC9DB6A07ED26721DD0DA0186B,山东吉尔德环境工程有限公司,14.0,0.0,0,14.0
98324,8C2F86DC1FFF27CD947AEF4F44E3F949,南京板桥消防设备有限责任公司,22.0,1.0,0,21.0
114533,3AFA4454A5211CF7C60124921C6AB1E5,郑州鸿贝科技股份有限公司,13.0,1.0,0,12.0
123567,6B78BA3C3EBA5D0ACF5BAA00E73AEA5C,陕西墨氏石墨烯科技有限公司,14.0,0.0,0,14.0
156819,20962B9CF1B73DB05E385CCDF2CAACDB,湖南龙盾安防设备有限公司,37.0,1.0,0,36.0
156971,305C15B6D22BEE5CFE12F45A3D66C878,深圳市威立讯电子有限公司,13.0,1.0,0,12.0
157870,81C89B7D83D863AE50429CB9D3809D45,上海赛复安防科技有限公司,45.0,0.0,0,45.0
171086,35802D38CDE21A0E8A35242A1A1235A5,湖北三禾建材科技发展有限责任公司,21.0,0.0,0,21.0
173496,123B4DFB362ADF6A239B98FC34A1237F,四川维优科技有限责任公司,13.0,0.0,0,13.0
174219,58122FD3708EE64E876DAE3B26C81711,叠云（北京）科技股份有限公司,27.0,1.0,0,26.0
176590,303ADF6CC45320D60823DB663F72568A,晋州市安达汽车配件有限公司,15.0,1.0,0,14.0
186650,C1336DF7862EECBA0D523BA3B16E79CB,郑州英鹏汽车部件有限公司,19.0,1.0,0,18.0
192638,E19F7469B66CBFA20E02C1D6C3C0F5E7,辽宁金兴汽车内饰有限公司,32.0,1.0,0,31.0
219806,923B467CA3030433CC9D9DC2676261FF,邦优杰智慧节能科技有限公司,13.0,1.0,0,12.0
221304,191F093AEFFD21E1BFD2142F7DC5271B,宁波海莲电器科技有限公司,11.0,0.0,0,11.0
222041,5EF36D55EFC4B31ADD46AFDAFCBA3811,中山市威世曼供热设备有限公司,35.0,1.0,0,34.0
223017,B42B1DD41E23ED619BD41662BE2A04E5,浙江巨泽科技有限公司,23.0,0.0,0,23.0
229312,F514A13D64E4ADB78445BECF441A645F,湖南江南汽车制造有限公司,54.0,1.0,0,53.0
245443,B76C5B29B7609B25737C98B96A889106,深圳市康奈可科技有限公司,12.0,1.0,0,11.0
245494,BBEC6E4A3B318F238E700573C40137C5,杭州光阳动力技术有限公司,14.0,0.0,0,14.0
270097,8880FDC5B3922D8100D2FA1AA1EAC076,亚萨合莱保德安（台州）安防科技有限公司,15.0,0.0,0,15.0
270190,92AF6E403DAD1AF6747E01D2DCF96D47,山东蓝诺汽车有限公司,39.0,0.0,0,39.0
270870,CBFBD2ED105D4B3394044ABC6FED5F14,艾特克控股集团股份有限公司,12.0,1.0,0,11.0
275229,5D516D1B3C3632A64B77C401FBA541D1,盘锦兴隆宝通实业有限公司,20.0,1.0,0,19.0
281813,B329FE4645C9FE1F87AF68BA14C9AEF1,晋江力利玩具有限公司,14.0,1.0,0,13.0
284974,CC03845EA5DD74F09D2E1770B817D548,安徽贝瓦电气有限公司,14.0,0.0,0,14.0
288988,40C543BDADE5A44F1042D8EC94A44705,佛山市友人科技有限公司,15.0,1.0,0,14.0
291752,38D40AFF1BEC4481C5C342EE63CB1832,安徽灵感科技股份有限公司,11.0,1.0,0,10.0
301041,91D33B9E55686F9B408F891C335BB7DE,永康市利泽维工贸有限公司,15.0,1.0,0,14.0
305803,445F61CE753407BDC57714B8F9D6AC05,北京元一车饰有限公司,14.0,1.0,0,13.0
316774,3AC4CB1A70A45EC703C12CB2BEA0C609,中山市宝蓓悠日用制品有限公司,13.0,1.0,0,12.0
322207,294972EAE08E68EB130EB7425CEAC564,广州虹亿车辆配件有限公司,11.0,0.0,0,11.0
343883,F10552321D600872F3F485334916EF85,苏州朗格电气有限公司,16.0,1.0,0,15.0
345419,7D5FBD3E2F98825EFEAD421845770163,辽源市佳林造革有限责任公司,15.0,1.0,0,14.0
346194,C7115904519BDD8E69501A4AA88E6932,山东吉孚消防科技有限公司,17.0,1.0,0,16.0
352656,1AE327C3C1BA9404E28EB94C2B4CD4A2,四川水之子环保科技有限公司,14.0,0.0,0,14.0
354242,AF6B6819E37D1A4B71E028AC5C101763,广州中誉电器有限公司,13.0,1.0,0,12.0
366218,005CE70D801178045A6388F60B5A4629,四川瑞思可消防科技有限公司,18.0,0.0,0,18.0
369189,0CD4152CB537337CFA6B45174A98E100,合肥宝龙达信息技术有限公司,27.0,1.0,0,26.0
374006,C1F6B303BB3A772AA835E83DF2E4B1AC,佛山市钜华电器有限公司,11.0,1.0,0,10.0
378686,6DE365C087937B9C079920520637CBDF,济南矿用电器有限公司,13.0,0.0,0,13.0
388152,CC5B3AFE0FB007DA9C297E63C662F28A,浙江瑞邦汽车零部件有限公司,12.0,1.0,0,11.0
389950,75695CCE9224D28C399244089F1F61D9,中山市传美奇电器有限公司,18.0,1.0,0,17.0
411756,3FB04BCCFB7757160088CB8CCF25A7F3,云南凯沃达汽车饰件有限公司,21.0,0.0,0,21.0
432980,D3B0F01E813AC933BA1B08F9A9F61A09,廊坊英固贸易有限责任公司,28.0,1.0,0,27.0
438282,BC9D4C1639EC9534F7B73E9BAFBC6AAF,浙江洲辰电气有限公司,12.0,0.0,0,12.0
443836,BD23A9609EA3C8A2BE765E050C2E450F,江苏森远汽车部件有限公司,22.0,0.0,0,22.0
452073,B2DF56C87988BC221856C4E95875B656,北京金峰华玉空调设备安装工程有限公司,24.0,0.0,0,24.0
455044,C276661C04943B7B97B186D964DA2447,温州菱光电器机械制造有限公司,16.0,1.0,0,15.0
460748,CD13B518C54AAFCC479740EFC33C1737,威宝工业（惠州）有限公司,12.0,1.0,0,11.0
475779,36C5829D9A857B44CFDCEA29A8CC66B6,广东飞轮科技股份有限公司,11.0,1.0,0,10.0
476090,54E7330FBE411217915BD14DFDB55360,东莞市鑫诠光电技术有限公司,14.0,1.0,0,13.0
480596,EF93027BF30578E185430933032BB1F9,伊顿电气（天津）有限公司,12.0,0.0,0,12.0
481140,228A6549BC79E2CC197BF16DD5719D49,江苏天诚车饰科技有限公司,17.0,1.0,0,16.0
481448,3FA8FE3EDEEFD51F24D3344534746059,东莞市德尔能新能源股份有限公司,15.0,0.0,0,15.0
502115,AC653E00B862BACF0F29220AC3823518,南京市安略能源设备有限公司,25.0,0.0,0,25.0
506133,212491ED93081218A1907E75884DA961,广东纳美仕电器有限公司,14.0,1.0,0,13.0
508702,0925AF0502973D8082742054A476EDC6,山东迈凯诺安防科技有限公司,17.0,1.0,0,16.0
512244,5449C9B60AEE27877A484DD2A32C9C57,北京华通恒盛电气设备有限公司,13.0,0.0,0,13.0
513585,CFB76AEC6987BDD291B52D58EE0824AD,昆山百瑞康儿童用品有限公司,16.0,1.0,0,15.0
515702,8C4A90ED782907F07FC04364E98F07A0,陕西通家汽车股份有限公司,36.0,1.0,0,35.0
518005,5CAE826274E1D800DA0FA20921EE6318,锦州市好为尔保温材料有限公司,11.0,1.0,0,10.0
525020,E382723809428596FA7AAC6335108C3F,中山壹朵光电科技有限公司,14.0,1.0,0,13.0
528789,3DB271CE554DE3D72B750B6483B55EB4,佛山市峻生通风设备有限公司,26.0,0.0,0,26.0
540301,5F41DBAD475ADAC027AB02F5B5DAFC61,华晨专用车装备科技（大连）有限公司,31.0,1.0,0,30.0
548483,4D74E3505D92A3F25CFEF70869079775,苏州芯创智汇电子科技有限公司,13.0,0.0,0,13.0
551461,673FE4D5B22DD6017079B70D325BBDBA,廊坊速瑞电子技术有限公司,11.0,1.0,0,10.0
554292,6C05BAF90780993BD9CE674C05A0D75C,深圳市吉音科技发展有限公司,17.0,0.0,0,17.0
559419,40906ABCF57F9EEC9AEEAD1CC4A18C5F,四川长虹通信科技有限公司,40.0,1.0,0,39.0
562192,44C729F77B9164678C9F5A27DD14B79B,佛山市顺德区冠迪电器实业有限公司,12.0,1.0,0,11.0
562344,52628011A761CBCE00134E595BD52E02,云南京云消防通风设备有限公司,33.0,1.0,0,32.0
564628,20D1B68D012D0093511C1621F88B4BA2,河南凌云制冷设备有限公司,22.0,1.0,0,21.0
571082,75B7B27AB35283C870CC3BFE4D3EFC46,广东柏泰门业有限公司,47.0,1.0,0,46.0
571388,921E036D6B07AB473B92EAF7C56BD59B,荣成市裕铭餐饮设备有限公司,11.0,1.0,0,10.0
572489,FCF8FF87B7199946EC703E96CE2FE239,洛阳银燕科技有限公司,11.0,0.0,0,11.0
578255,0CB66E447DA2E6E0C00C88099E9F43DC,北京鸿盛天启科技有限公司,15.0,0.0,0,15.0
582409,91E153003D7ADCFCE7D1A66CB04867A0,金华青年汽车制造有限公司,25.0,1.0,0,24.0
582451,94B01A68695A765EC5E0DF3ABCB5D180,江门市威多福电器有限公司,25.0,1.0,0,24.0
582629,A5042084CD36AFAC2A179A147F754603,嘉兴仙视电子有限公司,30.0,0.0,0,30.0
598588,69E9463D4C3D7E750E355CBF7786477A,重庆嘉威特节能玻璃有限公司,18.0,0.0,0,18.0
616672,F3433A0EEAECA6B73D24515BBF17B7EC,山西腾行智能科技有限公司,14.0,1.0,0,13.0
619079,C99102F5C60ADD3EB25E2D01F015B009,青海龙霖热能科技有限责任公司,29.0,0.0,0,29.0
620465,4B69AA685E2943B89575C5EF2E930F52,福建俊豪科技有限公司,13.0,0.0,0,13.0
625837,39B3492AED808EA2776B4194B4535427,中山市威雅电器燃具有限公司,14.0,0.0,0,14.0
626139,5738B5152501EBB35AC0FF5416F74E4B,重庆幻速汽车配件有限公司,27.0,0.0,0,27.0
630807,06B58E27CFF42F0D6B6A8F28601A1228,广州艾考教育科技有限公司,13.0,1.0,0,12.0

In [14]:
certificates[certificates['change']==0]

,company_id,num_certificates,num_certificates_valid,change
7,00B7A232CC0D73DFE36EE4BD25E40E05,1.0,0.0,0
25,02BEC1E8A5673AC8BD10AD040C21FF7D,2.0,1.0,0
32,03017316E4173808B24E85282F9CF932,5.0,4.0,0
36,037C7D1CEAB3856D73C8298771AC1238,7.0,3.0,0
57,054A6E1F31C851AFE6DB5CB245D35DCC,1.0,0.0,0
...,...,...,...,...
1109310,FADE4835C3E89B9802C9C1B56D437B6B,1.0,0.0,0
1109320,FC6F647F6921ABFECAAB9A18CFDA5C81,5.0,4.0,0
1109335,FE6AF2DD6D039435DFF1E7522009DB2B,1.0,0.0,0
1109348,FFB2CCFAC37353C551D5377EEC23108F,3.0,2.0,0
1109351,FFE318C4EA741399699C17DE9C533DC7,6.0,5.0,0

In [225]:
looping_test_feature_switch_sse_company_nonpatent_indicators.query('company_id=="A70A3E493E6B6E9C3D1CDA03B6279CAA"').T

                                                               929734
company_id                           A70A3E493E6B6E9C3D1CDA03B6279CAA
duration                                                    34.673973
actual_capital_formatted                                40341131820.0
reg_capital_formatted                                   40441131820.0
qualify_certificate                      国家企业技术中心__高新技术企业__国家技术创新示范企业
ans_id                           f039e90a-679c-4c50-ab06-72d03d496c4f
company_name                                                 华为技术有限公司
seic_lv1                                                    新一代信息技术产业
seic_lv2                                                    下一代信息网络产业
province                                                          广东省
city                                                              深圳市
status                                                         ACTIVE
public                                                            NaN
rounds                                                            NaN
money_q25_sum_weighted                                            NaN
most_recent_money_q25_formatted                                   NaN
most_recent_time                                                  NaN
avg_funding_interval                                              NaN
reg_num                                                         676.0
reg_num_5y                                                      304.0
reg_growth_ratio                                             0.283745
reg_3y_avg                                                  68.666667
num_trademarks_registered                                      5858.0
num_trademarks_total                                           9610.0
num_trademarks_registered_5y                                   4365.0
num_trademarks_total_5y                                        8083.0
num_certificates                                               3844.0
num_certificates_valid                                         2917.0
num_members                                                      68.0

### qualify_certificate

测试点：
1、测试含有有效资质公司的总量
2、抽取含有公司过期资质的公司，测试过期的资质是否去掉
3、抽取测试case，对比结果一致性

In [267]:
qualify_certificate=looping_test_feature_switch_sse_company_nonpatent_indicators[['company_id','ans_id','company_name',
                                                                  'seic_lv2','qualify_certificate']]
qualify_certificate

,company_id,ans_id,company_name,seic_lv2,qualify_certificate
0,000FA681D1E7610073C53DA8CF8CF6A7,ed596d9b-ea93-41e5-a5d7-522ea72bae22,绵阳数智生物科技有限公司,生物医药产业,科技型中小企业
1,0014A83C9B038292B6E0DB202479DEB9,NaN,苏州载道网络科技有限公司,新兴软件和新型信息技术服务,NaN
2,001CE08C53F7BD9A821358DD21C50C88,NaN,中航证券有限公司,其他相关服务,NaN
3,0067F4DD86BE9866BD8E617D2B88E821,5de5cd27-7cc7-4b88-b482-cf7ce5811143,重庆纳川山隅重工设备有限公司,智能制造装备产业,NaN
4,006A322857D17795374D7749C2C32538,e9aa448c-09db-4d69-8176-3368e8812bf7,中山市钜泰硅胶科技有限公司,先进无机非金属材料,高新技术企业__科技型中小企业
...,...,...,...,...,...
1109774,C7C049CDA7F42E6D89B2D5351D6B0412,NaN,NaN,NaN,NaN
1109775,C85082D305A61A9633616A87858E156B,NaN,NaN,NaN,NaN
1109776,E586B12C6FBDBE45B224378D90FE78A8,NaN,NaN,NaN,NaN
1109777,F74C48AD2E7CF455975FBF6C1BC9F29C,NaN,NaN,NaN,NaN
1109778,FD9510BB0B4C5092BFEB060E5B3AFD91,NaN,NaN,NaN,NaN

In [43]:
qualify_certificate[qualify_certificate['qualify_certificate'].notnull()]

,company_id,ans_id,company_name,seic_lv2,qualify_certificate
0,000FA681D1E7610073C53DA8CF8CF6A7,ed596d9b-ea93-41e5-a5d7-522ea72bae22,绵阳数智生物科技有限公司,生物医药产业,科技型中小企业
4,006A322857D17795374D7749C2C32538,e9aa448c-09db-4d69-8176-3368e8812bf7,中山市钜泰硅胶科技有限公司,先进无机非金属材料,高新技术企业__科技型中小企业
5,0097CB3253FA5EBCE4BB882305ACB03A,28242ee9-180e-4301-8601-5c42ed2f8f0c,马鞍山市德善金属成型科技有限公司,先进有色金属材料,高新技术企业__安徽省专精特新
9,00D6CAD68E52953C9922B3AB737CEDC0,NaN,上海铱芯信息科技有限公司,新兴软件和新型信息技术服务,科技型中小企业
11,00F44911E943CA0DDA7BFF228A25AE33,fdc46f1a-cb8e-46a3-ac65-1e0589c91285,南通启汇电子有限公司,其它,科技型中小企业
...,...,...,...,...,...
1109337,FE7FD982CC0FD9DF821A78CB5F9DCF63,NaN,自贡友元环保科技有限公司,先进环保产业,科技型中小企业
1109340,FEF7ECB78AE80ED75E3914E675A7421B,e0079705-0d66-42e0-bf8b-f32d297e3208,成都畅达通检测技术股份有限公司,新技术与创新创业服务,高新技术企业__科技型中小企业
1109342,FF21C6D8BC758928BCC2A5B6F411318A,b72c1c50-1e41-45a1-8c07-0f8162b00fa8,上海创程车联网络科技有限公司,下一代信息网络产业,高新技术企业
1109344,FF55E3264CFCD701C92203516FE1A7D3,9b729f15-ec59-404b-849e-0fdc8b4b97c3,上海乔源智能化设备有限公司,人工智能,科技型中小企业
1109348,FFB2CCFAC37353C551D5377EEC23108F,f10f02ed-152b-4721-b6e6-5331eb5860f5,滁州岳众汽车零部件有限公司,其它,高新技术企业__科技型中小企业

In [268]:
qualify_certificate.query('company_id=="A70A3E493E6B6E9C3D1CDA03B6279CAA"')

,company_id,ans_id,company_name,seic_lv2,qualify_certificate
929734,A70A3E493E6B6E9C3D1CDA03B6279CAA,f039e90a-679c-4c50-ab06-72d03d496c4f,华为技术有限公司,下一代信息网络产业,国家企业技术中心__高新技术企业__国家技术创新示范企业

### num_certificates_valid

测试点：
1、测试含有有效资质证书的公司数量是否等于certificate_status状态等于有效或其它，并且deadline大于当前时间
2、测试certificate_status或deadline为空的数据计算时是否统计
3、抽取测试case，对比结果一致性

In [55]:
num_certificates_valid=looping_test_feature_switch_sse_company_nonpatent_indicators[['company_id','ans_id','company_name',
                                                                  'seic_lv2','num_certificates_valid']]
num_certificates_valid

,company_id,ans_id,company_name,seic_lv2,num_certificates_valid
0,000FA681D1E7610073C53DA8CF8CF6A7,ed596d9b-ea93-41e5-a5d7-522ea72bae22,绵阳数智生物科技有限公司,生物医药产业,NaN
1,0014A83C9B038292B6E0DB202479DEB9,NaN,苏州载道网络科技有限公司,新兴软件和新型信息技术服务,NaN
2,001CE08C53F7BD9A821358DD21C50C88,NaN,中航证券有限公司,其他相关服务,NaN
3,0067F4DD86BE9866BD8E617D2B88E821,5de5cd27-7cc7-4b88-b482-cf7ce5811143,重庆纳川山隅重工设备有限公司,智能制造装备产业,NaN
4,006A322857D17795374D7749C2C32538,e9aa448c-09db-4d69-8176-3368e8812bf7,中山市钜泰硅胶科技有限公司,先进无机非金属材料,2.0
...,...,...,...,...,...
1109774,C7C049CDA7F42E6D89B2D5351D6B0412,NaN,NaN,NaN,NaN
1109775,C85082D305A61A9633616A87858E156B,NaN,NaN,NaN,NaN
1109776,E586B12C6FBDBE45B224378D90FE78A8,NaN,NaN,NaN,NaN
1109777,F74C48AD2E7CF455975FBF6C1BC9F29C,NaN,NaN,NaN,NaN
1109778,FD9510BB0B4C5092BFEB060E5B3AFD91,NaN,NaN,NaN,NaN

In [281]:
looping_test_feature_switch_sse_company_nonpatent_indicators.query('company_id=="A70A3E493E6B6E9C3D1CDA03B6279CAA"')[['company_id','num_certificates_valid']]

                              company_id  num_certificates_valid
929734  A70A3E493E6B6E9C3D1CDA03B6279CAA                  2917.0

In [60]:
num_certificates_valid[num_certificates_valid['num_certificates_valid'].notnull()]

,company_id,ans_id,company_name,seic_lv2,num_certificates_valid
4,006A322857D17795374D7749C2C32538,e9aa448c-09db-4d69-8176-3368e8812bf7,中山市钜泰硅胶科技有限公司,先进无机非金属材料,2.0
5,0097CB3253FA5EBCE4BB882305ACB03A,28242ee9-180e-4301-8601-5c42ed2f8f0c,马鞍山市德善金属成型科技有限公司,先进有色金属材料,4.0
10,00E0C127D47E8F4944B61BD0B4B8BACF,NaN,昆山恺博传动系统有限公司,智能制造装备产业,1.0
12,00FF6CBBF0320CB4961643084A2C6B0D,2fa9614b-d4a8-46de-a856-3f1f43f0cdc4,苏州运恒精冲科技有限公司,先进钢铁材料,3.0
16,015189558512396A2936336B9CAC6E5F,13014be5-851f-44b0-af45-5e5e2e1f823f,宁夏启玉生物新材料有限公司,生物农业及相关产业,1.0
...,...,...,...,...,...
1109342,FF21C6D8BC758928BCC2A5B6F411318A,b72c1c50-1e41-45a1-8c07-0f8162b00fa8,上海创程车联网络科技有限公司,下一代信息网络产业,2.0
1109345,FF7321F5E1966F60F9918A635A0F704B,c8adac7c-8051-11ec-bb99-aa1cc5da68a3,广东忠信生物科技有限公司,生物医药产业,1.0
1109348,FFB2CCFAC37353C551D5377EEC23108F,f10f02ed-152b-4721-b6e6-5331eb5860f5,滁州岳众汽车零部件有限公司,其它,2.0
1109349,FFB6D6F6BE7C5ED2550299D6094F9C71,ac2dce3b-d444-409e-9276-60012bfc2469,浙江大升旅行用品科技股份有限公司,其它,1.0
1109351,FFE318C4EA741399699C17DE9C533DC7,NaN,厦门文杉信息科技有限公司,互联网与云计算、大数据服务,5.0

### num_certificates

测试点：
1、测试含有有效资质证书的公司数量是否等于deadline大于当前时间
2、测试deadline为空的数据计算时是否统计
3、抽取测试case，对比结果一致性

In [78]:
num_certificates=looping_test_feature_switch_sse_company_nonpatent_indicators[['company_id','ans_id','company_name',
                                                                  'seic_lv2','num_certificates']]
num_certificates

,company_id,ans_id,company_name,seic_lv2,num_certificates
0,000FA681D1E7610073C53DA8CF8CF6A7,ed596d9b-ea93-41e5-a5d7-522ea72bae22,绵阳数智生物科技有限公司,生物医药产业,NaN
1,0014A83C9B038292B6E0DB202479DEB9,NaN,苏州载道网络科技有限公司,新兴软件和新型信息技术服务,NaN
2,001CE08C53F7BD9A821358DD21C50C88,NaN,中航证券有限公司,其他相关服务,NaN
3,0067F4DD86BE9866BD8E617D2B88E821,5de5cd27-7cc7-4b88-b482-cf7ce5811143,重庆纳川山隅重工设备有限公司,智能制造装备产业,NaN
4,006A322857D17795374D7749C2C32538,e9aa448c-09db-4d69-8176-3368e8812bf7,中山市钜泰硅胶科技有限公司,先进无机非金属材料,2.0
...,...,...,...,...,...
1109774,C7C049CDA7F42E6D89B2D5351D6B0412,NaN,NaN,NaN,NaN
1109775,C85082D305A61A9633616A87858E156B,NaN,NaN,NaN,NaN
1109776,E586B12C6FBDBE45B224378D90FE78A8,NaN,NaN,NaN,NaN
1109777,F74C48AD2E7CF455975FBF6C1BC9F29C,NaN,NaN,NaN,NaN
1109778,FD9510BB0B4C5092BFEB060E5B3AFD91,NaN,NaN,NaN,NaN

In [79]:
num_certificates[num_certificates['num_certificates'].notnull()]

,company_id,ans_id,company_name,seic_lv2,num_certificates
4,006A322857D17795374D7749C2C32538,e9aa448c-09db-4d69-8176-3368e8812bf7,中山市钜泰硅胶科技有限公司,先进无机非金属材料,2.0
5,0097CB3253FA5EBCE4BB882305ACB03A,28242ee9-180e-4301-8601-5c42ed2f8f0c,马鞍山市德善金属成型科技有限公司,先进有色金属材料,4.0
7,00B7A232CC0D73DFE36EE4BD25E40E05,b51be918-8175-4bfe-9b44-50647094dcae,福建美美饰股份有限公司,其它,1.0
10,00E0C127D47E8F4944B61BD0B4B8BACF,NaN,昆山恺博传动系统有限公司,智能制造装备产业,1.0
12,00FF6CBBF0320CB4961643084A2C6B0D,2fa9614b-d4a8-46de-a856-3f1f43f0cdc4,苏州运恒精冲科技有限公司,先进钢铁材料,3.0
...,...,...,...,...,...
1109342,FF21C6D8BC758928BCC2A5B6F411318A,b72c1c50-1e41-45a1-8c07-0f8162b00fa8,上海创程车联网络科技有限公司,下一代信息网络产业,2.0
1109345,FF7321F5E1966F60F9918A635A0F704B,c8adac7c-8051-11ec-bb99-aa1cc5da68a3,广东忠信生物科技有限公司,生物医药产业,1.0
1109348,FFB2CCFAC37353C551D5377EEC23108F,f10f02ed-152b-4721-b6e6-5331eb5860f5,滁州岳众汽车零部件有限公司,其它,3.0
1109349,FFB6D6F6BE7C5ED2550299D6094F9C71,ac2dce3b-d444-409e-9276-60012bfc2469,浙江大升旅行用品科技股份有限公司,其它,1.0
1109351,FFE318C4EA741399699C17DE9C533DC7,NaN,厦门文杉信息科技有限公司,互联网与云计算、大数据服务,6.0

In [274]:
looping_test_feature_switch_sse_company_nonpatent_indicators.query('company_id=="A70A3E493E6B6E9C3D1CDA03B6279CAA"')[['company_id','num_certificates']]

                              company_id  num_certificates
929734  A70A3E493E6B6E9C3D1CDA03B6279CAA            3844.0

### actual_capital_formatted

测试点
1、测试实缴资本为空跟为为0的数量
2、测试实缴资本货币的汇率
3、抽取测试case，对比结果一致性

In [284]:
actual_capital_formatted=looping_test_feature_switch_sse_company_nonpatent_indicators[['company_id','ans_id','company_name',
                                                                  'seic_lv2','actual_capital_formatted']]
actual_capital_formatted

,company_id,ans_id,company_name,seic_lv2,actual_capital_formatted
0,000FA681D1E7610073C53DA8CF8CF6A7,ed596d9b-ea93-41e5-a5d7-522ea72bae22,绵阳数智生物科技有限公司,生物医药产业,0.000000e+00
1,0014A83C9B038292B6E0DB202479DEB9,NaN,苏州载道网络科技有限公司,新兴软件和新型信息技术服务,0.000000e+00
2,001CE08C53F7BD9A821358DD21C50C88,NaN,中航证券有限公司,其他相关服务,3.633573e+09
3,0067F4DD86BE9866BD8E617D2B88E821,5de5cd27-7cc7-4b88-b482-cf7ce5811143,重庆纳川山隅重工设备有限公司,智能制造装备产业,0.000000e+00
4,006A322857D17795374D7749C2C32538,e9aa448c-09db-4d69-8176-3368e8812bf7,中山市钜泰硅胶科技有限公司,先进无机非金属材料,2.000000e+06
...,...,...,...,...,...
1109774,C7C049CDA7F42E6D89B2D5351D6B0412,NaN,NaN,NaN,NaN
1109775,C85082D305A61A9633616A87858E156B,NaN,NaN,NaN,NaN
1109776,E586B12C6FBDBE45B224378D90FE78A8,NaN,NaN,NaN,NaN
1109777,F74C48AD2E7CF455975FBF6C1BC9F29C,NaN,NaN,NaN,NaN
1109778,FD9510BB0B4C5092BFEB060E5B3AFD91,NaN,NaN,NaN,NaN

In [285]:
looping_test_feature_switch_sse_company_nonpatent_indicators.query('company_id=="A70A3E493E6B6E9C3D1CDA03B6279CAA"')[['company_id','actual_capital_formatted']]

                              company_id  actual_capital_formatted
929734  A70A3E493E6B6E9C3D1CDA03B6279CAA              4.034113e+10

In [127]:
b=150*4.1
b

615.0

In [89]:
a=233588+124007
a

357595

In [88]:
actual_capital_formatted[actual_capital_formatted['actual_capital_formatted']==0]

,company_id,ans_id,company_name,seic_lv2,actual_capital_formatted
0,000FA681D1E7610073C53DA8CF8CF6A7,ed596d9b-ea93-41e5-a5d7-522ea72bae22,绵阳数智生物科技有限公司,生物医药产业,0.0
1,0014A83C9B038292B6E0DB202479DEB9,NaN,苏州载道网络科技有限公司,新兴软件和新型信息技术服务,0.0
3,0067F4DD86BE9866BD8E617D2B88E821,5de5cd27-7cc7-4b88-b482-cf7ce5811143,重庆纳川山隅重工设备有限公司,智能制造装备产业,0.0
6,00A0E0A68BC2DE2BE695BB9791660817,cb462e57-72df-4e54-82d1-8e81bc1410e0,广东青梅宝宝食品有限公司,其它,0.0
8,00D4305688D93C81A4A6FA44EB151109,111039a1-22ed-4674-b5bd-0ff71911d287,季正（天津）科技有限公司,新技术与创新创业服务,0.0
...,...,...,...,...,...
1109335,FE6AF2DD6D039435DFF1E7522009DB2B,a583e05d-6c36-42e6-b1af-2b088029935d,成都小麦花网络技术有限公司,互联网与云计算、大数据服务,0.0
1109338,FECBA9D073D2A46F4882E5A30611819E,NaN,上海胖橘网络科技有限公司,数字文化创意活动,0.0
1109343,FF336FAE061CB2E0DCAE348C52749A30,f2770efa-2815-415c-9de1-35636ab73f1a,河北桑巴多信息科技有限公司,互联网与云计算、大数据服务,0.0
1109345,FF7321F5E1966F60F9918A635A0F704B,c8adac7c-8051-11ec-bb99-aa1cc5da68a3,广东忠信生物科技有限公司,生物医药产业,0.0
1109346,FF90F1F21D0998DB02A2D3BBB506BF0E,9440982b-8a64-4fd7-be19-5ec5629a0ac1,山东九泽智能科技有限公司,新兴软件和新型信息技术服务,0.0

### reg_capital_formatted

测试点
1、测试注册资本为空跟为为0的数量一致性
2、测试注册资本货币的汇率
3、抽取测试case，对比结果一致性

In [288]:
reg_capital_formatted=looping_test_feature_switch_sse_company_nonpatent_indicators[['company_id','ans_id','company_name',
                                                                  'seic_lv2','reg_capital_formatted']]
reg_capital_formatted

,company_id,ans_id,company_name,seic_lv2,reg_capital_formatted
0,000FA681D1E7610073C53DA8CF8CF6A7,ed596d9b-ea93-41e5-a5d7-522ea72bae22,绵阳数智生物科技有限公司,生物医药产业,3.000000e+06
1,0014A83C9B038292B6E0DB202479DEB9,NaN,苏州载道网络科技有限公司,新兴软件和新型信息技术服务,1.000000e+06
2,001CE08C53F7BD9A821358DD21C50C88,NaN,中航证券有限公司,其他相关服务,3.633573e+09
3,0067F4DD86BE9866BD8E617D2B88E821,5de5cd27-7cc7-4b88-b482-cf7ce5811143,重庆纳川山隅重工设备有限公司,智能制造装备产业,7.000000e+06
4,006A322857D17795374D7749C2C32538,e9aa448c-09db-4d69-8176-3368e8812bf7,中山市钜泰硅胶科技有限公司,先进无机非金属材料,2.000000e+06
...,...,...,...,...,...
1109774,C7C049CDA7F42E6D89B2D5351D6B0412,NaN,NaN,NaN,NaN
1109775,C85082D305A61A9633616A87858E156B,NaN,NaN,NaN,NaN
1109776,E586B12C6FBDBE45B224378D90FE78A8,NaN,NaN,NaN,NaN
1109777,F74C48AD2E7CF455975FBF6C1BC9F29C,NaN,NaN,NaN,NaN
1109778,FD9510BB0B4C5092BFEB060E5B3AFD91,NaN,NaN,NaN,NaN

In [134]:
reg_capital_formatted[reg_capital_formatted['reg_capital_formatted']==0]

,company_id,ans_id,company_name,seic_lv2,reg_capital_formatted
103,095E356D4E8FDAE28120076C25C6DD52,62099312-76a8-4269-8789-87db8468b1b7,迪欧国际贸易有限公司,其它,0.0
118,0B03E7BE5379F357C0EAC401D205683E,60e39c97-ae26-4b95-a59e-fee4a9b8fa63,广东富山玻璃机械有限公司,先进无机非金属材料,0.0
409,22F33F64D4921C7A570E6ADAFFF3D5BF,5d7deb9e-5152-4033-9a33-3236d2b7479a,中石化石油机械股份有限公司承德江钻分公司,海洋工程装备产业,0.0
597,34310B619AF4DB5C1EA1DC95FBD64BCF,NaN,NaN,NaN,0.0
674,3BAB127F44F75492D6B2CFD6AD03DCBA,c78a6a2b-b9f6-4a22-8862-9bbb0694a258,孝昌县鑫新养殖设备加工厂,生物农业及相关产业,0.0
...,...,...,...,...,...
1108007,7F9135BA1E1DCD411C1BBCE7E7811E49,148df362-c1ca-46d8-bf5c-817f80c1aa34,骏阳集团有限公司,先进有色金属材料,0.0
1108247,95E903E84C6E5C2369CAF26F503F859E,6fa8bd3c-8490-4b95-9aea-bb38b14c88c6,建溢金融财务有限公司,其它,0.0
1108437,A84DC929AA989669F5B710A6031318DA,af305d9c-94b2-4a4b-85dc-753389297a17,升辉控股有限公司,人工智能,0.0
1108525,B18766A969DF9F726542B2B77992BCA0,c3f0e823-3332-4ba4-b0ae-7f466514a8f2,长春一汽富维汽车零部件股份有限公司销售分公司,其它,0.0
1108856,D0DA636D93C5D3F0CEF07CE17D67E660,8daae48c-56a1-447e-843a-b682722c79df,奇材孵化有限公司,其它,0.0

In [289]:
reg_capital_formatted.query('company_id=="A70A3E493E6B6E9C3D1CDA03B6279CAA"')

,company_id,ans_id,company_name,seic_lv2,reg_capital_formatted
929734,A70A3E493E6B6E9C3D1CDA03B6279CAA,f039e90a-679c-4c50-ab06-72d03d496c4f,华为技术有限公司,下一代信息网络产业,4.044113e+10

In [157]:
a=700*4.1
a

2869.9999999999995

### money_q25_sum_weighted

测试点
1、测试汇率是否转成正确
2、抽取测试case，对比结果一致性

In [159]:
money_q25_sum_weighted=looping_test_feature_switch_sse_company_nonpatent_indicators[['company_id','ans_id','company_name',
                                                                  'seic_lv2','money_q25_sum_weighted']]
money_q25_sum_weighted

,company_id,ans_id,company_name,seic_lv2,money_q25_sum_weighted
0,000FA681D1E7610073C53DA8CF8CF6A7,ed596d9b-ea93-41e5-a5d7-522ea72bae22,绵阳数智生物科技有限公司,生物医药产业,NaN
1,0014A83C9B038292B6E0DB202479DEB9,NaN,苏州载道网络科技有限公司,新兴软件和新型信息技术服务,NaN
2,001CE08C53F7BD9A821358DD21C50C88,NaN,中航证券有限公司,其他相关服务,8275187.5
3,0067F4DD86BE9866BD8E617D2B88E821,5de5cd27-7cc7-4b88-b482-cf7ce5811143,重庆纳川山隅重工设备有限公司,智能制造装备产业,NaN
4,006A322857D17795374D7749C2C32538,e9aa448c-09db-4d69-8176-3368e8812bf7,中山市钜泰硅胶科技有限公司,先进无机非金属材料,NaN
...,...,...,...,...,...
1109774,C7C049CDA7F42E6D89B2D5351D6B0412,NaN,NaN,NaN,NaN
1109775,C85082D305A61A9633616A87858E156B,NaN,NaN,NaN,NaN
1109776,E586B12C6FBDBE45B224378D90FE78A8,NaN,NaN,NaN,NaN
1109777,F74C48AD2E7CF455975FBF6C1BC9F29C,NaN,NaN,NaN,NaN
1109778,FD9510BB0B4C5092BFEB060E5B3AFD91,NaN,NaN,NaN,NaN

In [161]:
money_q25_sum_weighted[money_q25_sum_weighted['money_q25_sum_weighted'].notnull()]

,company_id,ans_id,company_name,seic_lv2,money_q25_sum_weighted
2,001CE08C53F7BD9A821358DD21C50C88,NaN,中航证券有限公司,其他相关服务,8.275188e+06
10,00E0C127D47E8F4944B61BD0B4B8BACF,NaN,昆山恺博传动系统有限公司,智能制造装备产业,1.144583e+07
16,015189558512396A2936336B9CAC6E5F,13014be5-851f-44b0-af45-5e5e2e1f823f,宁夏启玉生物新材料有限公司,生物农业及相关产业,5.000000e+06
19,019E09E267C05E835C2BB957AE3F358A,NaN,成都银海启明医院管理有限公司,其它,1.000000e+07
37,038127C2A8F2487E7B1FCA3330CDABA0,da549079-4968-42b4-a8e1-c08f7d70ed52,重庆华悦生态环境工程研究院有限公司,先进环保产业,2.050000e+06
...,...,...,...,...,...
1109285,F8C69B70A798D6E67DFC993F56511EFE,NaN,广州学问信息科技有限公司,互联网与云计算、大数据服务,2.000000e+05
1109297,FA19A130B3CFC6ADEADA328A624EBCD9,4ef1d74c-9eb9-4fb2-a268-1f9c773268de,广州市城建开发集团名特网络发展有限公司,下一代信息网络产业,4.347826e+04
1109333,FE25F12EE039DD1872DB7AED9253F8BE,NaN,郑州全生农牧科技有限公司,生物农业及相关产业,3.375000e+07
1109338,FECBA9D073D2A46F4882E5A30611819E,NaN,上海胖橘网络科技有限公司,数字文化创意活动,1.537500e+06
1109339,FECE687245C1BF01EEB70650D7DAFDE7,70fbea9b-e1b8-4844-a36e-29ed33993434,北京卡富通盈科技有限公司,互联网与云计算、大数据服务,1.820040e+07

In [313]:
money_q25_sum_weighted.query('company_id=="382869F8C6F39D716E07A4F571B05129"')

,company_id,ans_id,company_name,seic_lv2,money_q25_sum_weighted
386512,382869F8C6F39D716E07A4F571B05129,c972756b-19fd-4e47-8c67-019b1848716a,美满芯盛（杭州）微电子有限公司,电子核心产业,500000.0

In [314]:
money_q25_sum_weighted.query('company_id=="57C89374224FC58E5F51032EDE3DD835"')

,company_id,ans_id,company_name,seic_lv2,money_q25_sum_weighted
631677,57C89374224FC58E5F51032EDE3DD835,bdd4fcfa-9f19-4a72-9764-cccc245afcbb,矽磐微电子（重庆）有限公司,电子核心产业,3.333333e+06

### public

测试点
1、测试public的数量是否一致
2、抽测测试case，对比结果一致性

In [319]:
looping_test_feature_switch_sse_company_nonpatent_indicators.query('company_id=="02E2B5505993DEE6009B5E40C1936E8F"')[['company_id','ans_id','company_name',
                                                                  'seic_lv2','public']]

,company_id,ans_id,company_name,seic_lv2,public
719191,02E2B5505993DEE6009B5E40C1936E8F,feffd9af-7774-4981-9729-6f1f20c79c75,烟台张裕葡萄酿酒股份有限公司,其它,A股

In [325]:
looping_test_feature_switch_sse_company_nonpatent_indicators[
    looping_test_feature_switch_sse_company_nonpatent_indicators['public'].notnull()][['company_id','public']]

                               company_id public
204      12FDB87639C672562BC16014B5E37D45    新三板
212      13A6F11185EE00CA9BDA55A78A81029C     A股
318      1AFAC5D791C1F547C8E955A768620FA0     A股
396      217821701C22450438C955B27908AE1B     A股
455      2794EFA83AACEEBDD8E9108349082384    新三板
...                                   ...    ...
1109011  E058AD3082A483A2C6EEEAB08B9AF45B    新三板
1109057  E49C50CBD520D17F2CA59CEEF2066758    新三板
1109095  E800AD3A38A536C7915266BFCCE48AF2    新三板
1109169  EE955F86069DC67F4F8C7695CB1734B4    新三板
1109340  FEF7ECB78AE80ED75E3914E675A7421B    新三板

[11005 rows x 2 columns]

In [328]:
looping_test_feature_switch_sse_company_nonpatent_indicators['public'].value_counts()

新三板    6292
A股     4713
Name: public, dtype: int64

In [332]:
looping_test_feature_switch_sse_company_nonpatent_indicators.query('company_id=="02E2B5505993DEE6009B5E40C1936E8F"')

,company_id,duration,actual_capital_formatted,reg_capital_formatted,qualify_certificate,ans_id,company_name,seic_lv1,seic_lv2,province,city,status,public,rounds,money_q25_sum_weighted,most_recent_money_q25_formatted,most_recent_time,avg_funding_interval,reg_num,reg_num_5y,reg_growth_ratio,reg_3y_avg,num_trademarks_registered,num_trademarks_total,num_trademarks_registered_5y,num_trademarks_total_5y,num_certificates,num_certificates_valid,num_members
719191,02E2B5505993DEE6009B5E40C1936E8F,24.657534,685464000.0,685464000.0,NaN,feffd9af-7774-4981-9729-6f1f20c79c75,烟台张裕葡萄酿酒股份有限公司,其它,其它,山东省,烟台市,ACTIVE,A股,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,890.0,969.0,270.0,342.0,5.0,5.0,32.0

# 集团公司指标标准化前

## looping_group

In [256]:
looping_group=pd.read_csv('/Users/caicaiqijun/智慧牙/数据/全国数据/全国数据得分/2022/5月/ 集团公司标准化字段/looping_group_20220509_sse_company_nonpatent_indicators.csv')

In [257]:
looping_group

,group_id,duration,actual_capital_formatted,reg_capital_formatted,ans_id,public,qualify_certificate,seic_lv1,seic_lv2,province,...,reg_num_5y,reg_growth_ratio,reg_3y_avg,num_trademarks_registered,num_trademarks_total,num_trademarks_registered_5y,num_trademarks_total_5y,num_certificates,num_certificates_valid,num_members
0,000FA681D1E7610073C53DA8CF8CF6A7,6.731507,0.000000e+00,3.000000e+06,ed596d9b-ea93-41e5-a5d7-522ea72bae22,[],['科技型中小企业'],生物产业,生物医药产业,四川省,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,NaN,NaN
1,0014A83C9B038292B6E0DB202479DEB9,4.994521,0.000000e+00,1.000000e+06,NaN,[],['江苏省民营科技企业'],新一代信息技术产业,新兴软件和新型信息技术服务,江苏省,...,53.0,-0.221501,6.666667,1.0,1.0,1.0,1.0,NaN,NaN,NaN
2,001CE08C53F7BD9A821358DD21C50C88,19.597260,3.633573e+09,3.633573e+09,NaN,[],"['高新技术企业', '科技型中小企业']",相关服务业,其他相关服务,江西省,...,43.0,0.607275,10.333333,7.0,10.0,1.0,4.0,18.0,7.0,NaN
3,0067F4DD86BE9866BD8E617D2B88E821,7.263014,0.000000e+00,7.000000e+06,5de5cd27-7cc7-4b88-b482-cf7ce5811143,[],[],高端装备制造产业,智能制造装备产业,重庆市,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,006A322857D17795374D7749C2C32538,10.145205,2.000000e+06,2.000000e+06,e9aa448c-09db-4d69-8176-3368e8812bf7,[],"['高新技术企业', '科技型中小企业']",新材料产业,先进无机非金属材料,广东省,...,NaN,NaN,NaN,2.0,2.0,0.0,0.0,3.0,2.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1110162,C7C049CDA7F42E6D89B2D5351D6B0412,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0
1110163,C85082D305A61A9633616A87858E156B,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22.0
1110164,E586B12C6FBDBE45B224378D90FE78A8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0
1110165,F74C48AD2E7CF455975FBF6C1BC9F29C,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0
1110166,FD9510BB0B4C5092BFEB060E5B3AFD91,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0

In [331]:
looping_group.query('group_id=="9502E1B5EDBAB4D66A1575245E66242D"')

,group_id,duration,actual_capital_formatted,reg_capital_formatted,ans_id,public,qualify_certificate,seic_lv1,seic_lv2,province,city,status,group_name,rounds,money_q25_sum_weighted,most_recent_money_q25_formatted,most_recent_time,avg_funding_interval,reg_num,reg_num_5y,reg_growth_ratio,reg_3y_avg,num_trademarks_registered,num_trademarks_total,num_trademarks_registered_5y,num_trademarks_total_5y,num_certificates,num_certificates_valid,num_members
765135,9502E1B5EDBAB4D66A1575245E66242D,21.224658,2.520000e+10,2.520000e+10,471d93c8-b64e-49bc-9059-0a47de4bfa6b,"['港股/美股', 'A股', '新三板']","['专精特新小巨人', '高新技术企业', '瞪羚企业', '单项冠军产品企业', '科技型中小企业']",新材料产业,先进有色金属材料,北京市,北京市,ACTIVE,中国铝业集团有限公司,49.0,2.660987e+08,1000000.0,0.624658,0.515696,465.0,370.0,0.041684,68.0,632.0,726.0,160.0,196.0,1240.0,440.0,2.0

### qualify_certificate

In [269]:
qualify_certificate=looping_group[['group_id','ans_id','seic_lv2','qualify_certificate']]
qualify_certificate

,group_id,ans_id,seic_lv2,qualify_certificate
0,000FA681D1E7610073C53DA8CF8CF6A7,ed596d9b-ea93-41e5-a5d7-522ea72bae22,生物医药产业,['科技型中小企业']
1,0014A83C9B038292B6E0DB202479DEB9,NaN,新兴软件和新型信息技术服务,['江苏省民营科技企业']
2,001CE08C53F7BD9A821358DD21C50C88,NaN,其他相关服务,"['高新技术企业', '科技型中小企业']"
3,0067F4DD86BE9866BD8E617D2B88E821,5de5cd27-7cc7-4b88-b482-cf7ce5811143,智能制造装备产业,[]
4,006A322857D17795374D7749C2C32538,e9aa448c-09db-4d69-8176-3368e8812bf7,先进无机非金属材料,"['高新技术企业', '科技型中小企业']"
...,...,...,...,...
1110162,C7C049CDA7F42E6D89B2D5351D6B0412,NaN,NaN,NaN
1110163,C85082D305A61A9633616A87858E156B,NaN,NaN,NaN
1110164,E586B12C6FBDBE45B224378D90FE78A8,NaN,NaN,NaN
1110165,F74C48AD2E7CF455975FBF6C1BC9F29C,NaN,NaN,NaN
1110166,FD9510BB0B4C5092BFEB060E5B3AFD91,NaN,NaN,NaN

In [303]:
qualify_certificate.query('group_id=="A70A3E493E6B6E9C3D1CDA03B6279CAA"')['qualify_certificate']

929734    ['瞪羚企业', '高新技术企业']
Name: qualify_certificate, dtype: object

### public

In [334]:
looping_group.query('group_id=="9502E1B5EDBAB4D66A1575245E66242D"')[['group_id','public']]

                                group_id                  public
765135  9502E1B5EDBAB4D66A1575245E66242D  ['港股/美股', 'A股', '新三板']

# 集团公司指标标准化后

## looping_group_switc

In [305]:
looping_group_switc=pd.read_csv('/Users/caicaiqijun/智慧牙/数据/全国数据/全国数据得分/2022/5月/ 集团公司标准化字段/looping_group_feature_switch_20220509_sse_company_nonpatent_indicators.csv')

In [306]:
looping_group_switc

,group_id,duration,actual_capital_formatted,reg_capital_formatted,qualify_certificate,ans_id,company_name,seic_lv1,seic_lv2,province,city,status,public,rounds,money_q25_sum_weighted,most_recent_money_q25_formatted,most_recent_time,avg_funding_interval,reg_num,reg_num_5y,reg_growth_ratio,reg_3y_avg,num_trademarks_registered,num_trademarks_total,num_trademarks_registered_5y,num_trademarks_total_5y,num_certificates,num_certificates_valid,num_members
0,000FA681D1E7610073C53DA8CF8CF6A7,6.739726,0.000000e+00,3.000000e+06,科技型中小企业,ed596d9b-ea93-41e5-a5d7-522ea72bae22,绵阳数智生物科技有限公司,生物产业,生物医药产业,四川省,绵阳市,ACTIVE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,0014A83C9B038292B6E0DB202479DEB9,5.002740,0.000000e+00,1.000000e+06,NaN,NaN,苏州载道网络科技有限公司,新一代信息技术产业,新兴软件和新型信息技术服务,江苏省,苏州市,ACTIVE,NaN,NaN,NaN,NaN,NaN,NaN,53.0,53.0,-0.221501,6.666667,1.0,1.0,1.0,1.0,NaN,NaN,NaN
2,001CE08C53F7BD9A821358DD21C50C88,19.605479,3.633573e+09,3.633573e+09,高新技术企业,NaN,中航证券有限公司,相关服务业,其他相关服务,江西省,南昌市,ACTIVE,NaN,5.0,3.073426e+07,40289575.0,0.624658,1.463699,43.0,43.0,0.607275,10.333333,7.0,10.0,1.0,4.0,8.0,7.0,NaN
3,0067F4DD86BE9866BD8E617D2B88E821,7.271233,0.000000e+00,7.000000e+06,NaN,5de5cd27-7cc7-4b88-b482-cf7ce5811143,重庆纳川山隅重工设备有限公司,高端装备制造产业,智能制造装备产业,重庆市,重庆市,ACTIVE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,006A322857D17795374D7749C2C32538,10.153425,2.000000e+06,2.000000e+06,科技型中小企业__高新技术企业,e9aa448c-09db-4d69-8176-3368e8812bf7,中山市钜泰硅胶科技有限公司,新材料产业,先进无机非金属材料,广东省,中山市,ACTIVE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2.0,0.0,0.0,2.0,2.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1109774,C7C049CDA7F42E6D89B2D5351D6B0412,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0
1109775,C85082D305A61A9633616A87858E156B,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22.0
1109776,E586B12C6FBDBE45B224378D90FE78A8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0
1109777,F74C48AD2E7CF455975FBF6C1BC9F29C,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0
1109778,FD9510BB0B4C5092BFEB060E5B3AFD91,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0

In [307]:
looping_group_switc.query('group_id=="A70A3E493E6B6E9C3D1CDA03B6279CAA"')

,group_id,duration,actual_capital_formatted,reg_capital_formatted,qualify_certificate,ans_id,company_name,seic_lv1,seic_lv2,province,city,status,public,rounds,money_q25_sum_weighted,most_recent_money_q25_formatted,most_recent_time,avg_funding_interval,reg_num,reg_num_5y,reg_growth_ratio,reg_3y_avg,num_trademarks_registered,num_trademarks_total,num_trademarks_registered_5y,num_trademarks_total_5y,num_certificates,num_certificates_valid,num_members
929734,A70A3E493E6B6E9C3D1CDA03B6279CAA,34.679452,4.034113e+10,4.044113e+10,国家技术创新示范企业__瞪羚企业__上海市企业技术中心__高新技术企业__国家企业技术中心,f039e90a-679c-4c50-ab06-72d03d496c4f,华为技术有限公司,新一代信息技术产业,下一代信息网络产业,广东省,深圳市,ACTIVE,NaN,5.0,1.220790e+08,66201500.0,0.386301,3.945205,1081.0,490.0,0.521337,122.666667,5969.0,9961.0,4465.0,8422.0,4050.0,3115.0,68.0

### qualify_certificate

In [308]:
looping_group_switc.query('group_id=="A70A3E493E6B6E9C3D1CDA03B6279CAA"')['qualify_certificate']

929734    国家技术创新示范企业__瞪羚企业__上海市企业技术中心__高新技术企业__国家企业技术中心
Name: qualify_certificate, dtype: object

###  num_certificates_valid

In [279]:
looping_group_switc.query('group_id=="A70A3E493E6B6E9C3D1CDA03B6279CAA"')[['group_id','num_certificates_valid']]

                                group_id  num_certificates_valid
929734  A70A3E493E6B6E9C3D1CDA03B6279CAA                  3115.0

### num_certificates

In [282]:
looping_group_switc.query('group_id=="A70A3E493E6B6E9C3D1CDA03B6279CAA"')[['group_id','num_certificates']]

                                group_id  num_certificates
929734  A70A3E493E6B6E9C3D1CDA03B6279CAA            4050.0

### actual_capital_formatted

In [283]:
looping_group_switc.query('group_id=="A70A3E493E6B6E9C3D1CDA03B6279CAA"')[['group_id','actual_capital_formatted']]

                                group_id  actual_capital_formatted
929734  A70A3E493E6B6E9C3D1CDA03B6279CAA              4.034113e+10

### reg_capital_formatted

In [286]:
looping_group_switc.query('group_id=="A70A3E493E6B6E9C3D1CDA03B6279CAA"')[['group_id','reg_capital_formatted']]

                                group_id  reg_capital_formatted
929734  A70A3E493E6B6E9C3D1CDA03B6279CAA           4.044113e+10

### money_q25_sum_weighted

In [312]:
looping_group_switc.query('group_id=="3A2989A4DBD7BAD2594518A8FF4F9A9F"')[['group_id','rounds']]

                                group_id  rounds
860100  3A2989A4DBD7BAD2594518A8FF4F9A9F     2.0

In [321]:
looping_group_switc.query('group_id=="A70A3E493E6B6E9C3D1CDA03B6279CAA"')[['group_id','public']]

                                group_id public
929734  A70A3E493E6B6E9C3D1CDA03B6279CAA    NaN

### public

In [323]:
looping_group_switc.query('group_id=="02E2B5505993DEE6009B5E40C1936E8F"')[['group_id','ans_id','company_name',
                                                                  'seic_lv2','public']]

,group_id,ans_id,company_name,seic_lv2,public
719191,02E2B5505993DEE6009B5E40C1936E8F,feffd9af-7774-4981-9729-6f1f20c79c75,烟台张裕葡萄酿酒股份有限公司,其它,A股

In [337]:
looping_group_switc['public'].notnull().sum()

11838

In [329]:
looping_group_switc['public'].value_counts()

新三板                     6598
A股                      4710
港股                       183
A股__港股                   170
A股__新三板                  132
A股__港股__中概股__美股           12
港股__新三板                   10
A股__港股__新三板               10
A股__港股__中概股                5
中概股__美股                    2
A股__中概股                    2
港股__中概股                    1
A股__中概股__新三板               1
A股__港股__美股__中概股__新三板       1
中概股                        1
Name: public, dtype: int64

In [330]:
looping_group_switc.query('public=="A股__港股__美股__中概股__新三板"')

,group_id,duration,actual_capital_formatted,reg_capital_formatted,qualify_certificate,ans_id,company_name,seic_lv1,seic_lv2,province,city,status,public,rounds,money_q25_sum_weighted,most_recent_money_q25_formatted,most_recent_time,avg_funding_interval,reg_num,reg_num_5y,reg_growth_ratio,reg_3y_avg,num_trademarks_registered,num_trademarks_total,num_trademarks_registered_5y,num_trademarks_total_5y,num_certificates,num_certificates_valid,num_members
765135,9502E1B5EDBAB4D66A1575245E66242D,21.232877,2.520000e+10,2.520000e+10,取消国家企业技术中心__湖北省隐形冠军示范__湖北省专精特新小巨人__专精特新小巨人__国家技术创新示范企业__单项冠军产品__北京市企业技术中心__国家企业技术中心__湖北省企业技术中心__高新技术企业__重庆市专精特新__江苏省企业技术中心__湖北省隐形冠军小巨人__贵州省企业技术中心__贵州省专精特新__科技型中小企业__山东省专精特新__山东省企业技术中心__河南省企业技术中心__瞪羚企业__河南省专精特新,471d93c8-b64e-49bc-9059-0a47de4bfa6b,中国铝业集团有限公司,新材料产业,先进有色金属材料,北京市,北京市,ACTIVE,A股__港股__美股__中概股__新三板,49.0,2.660987e+08,1000000.0,0.632877,0.515696,465.0,370.0,0.041684,68.0,632.0,726.0,160.0,196.0,436.0,419.0,2.0

# group

In [298]:
group=pd.read_csv('/Users/caicaiqijun/智慧牙/数据/全国数据/全国数据得分/2022/4月/子孙公司穿透/子孙穿透的集团公司.csv')
group.head(100)

                            group_id              group_name
0   F9AA5CEA611A455F2D548C02542ACEB3            南京云起信息科技有限公司
1   F9A9FC21F39CB84604DE52E06CF77E5A           宁德扬科狮虎进出口有限公司
2   F9A389392AB5A08B1994557220F8640A            湖南红门金属建材有限公司
3   F99CBAEEB39E5BF7566B03E3D2DEBDE8           湖南省华芯医疗器械有限公司
4   F9963A18ED2149CA64D66E173017334E           绍兴金渔纺织新技术有限公司
5   F993EB0E972A366DE42ED8F031FCC113              山东山孚集团有限公司
6   F98F46B5C50AECF24C4D06FFA483B7B0          泰州友润电子科技股份有限公司
7   F97E7E60F760DB1866FD0021755987B3            北京鸣天液压技术有限公司
8   F96DDC164E33125DB6361D36DBA6BBFC           肇庆市威盛塑料科技有限公司
9   F96A92C9FE6D5022B8D011479BFBEBE6            江苏风云科技服务有限公司
10  F954793AC12507FB239375186F0FE60D          上海摩威环境科技股份有限公司
11  F94E3D52812466E06768B4825E344EBF            北京泛博科技有限责任公司
12  F938D1BACF875A9E20D2393151A40B42              中慧农牧股份有限公司
13  F92BEA042DAC442A07EF06D6E768DFA8            重庆清平机械有限责任公司
14  F9298280AB0F6755CED5B6F4C0AF3199        广州浔沣轨道交通科技股份有限公司
15  F926938708F443C73A25E1DA201E783F              国能徐州发电有限公司
16  F920F634B8FA83453B00CB849462A006            深圳协鑫智慧能源有限公司
17  F920D8BB4057D125F93A0A8043F2A43C            国投电力控股股份有限公司
18  F91C00449AD46333773EB187723EFF92            嘉兴马灯照明科技有限公司
19  F9183574F9D0E115580384F87C54C099          河北荣泰模具科技股份有限公司
20  F9100222E7C0FF4ECBFAB41018BA5186           广东温和堂健康科学有限公司
21  F9065C168F784FF8D369C5EA5938DB12          中国交通信息科技集团有限公司
22  F902DD6FA5CC7E8D89D95054CF4F5768            上海景格科技股份有限公司
23  F8E38CAB843AFB279C71E0BF4753E3DE            上海讯析电子科技有限公司
24  F8E1AE21700E34210AE4113837B8E0F9          湛江国联水产种苗科技有限公司
25  F8DE0576DE1ABF387A3688DC0D418BD2       舒朋士环境科技（常州）股份有限公司
26  F8DAC795CA01A8F6198EADF0BEA84EBC           万卓（上海）新材料有限公司
27  F8D963EE03CA76202DDAF00F318A878C         苏州罗伦士汽车制造股份有限公司
28  F8CB9942E4FAB4B6611443E0FFF01B15      北京诚栋国际营地集成房屋股份有限公司
29  F8B0B142A95ED34EC7A55144B5E1EEC7           上海众多美网络科技有限公司
30  F8AD78DDE43F7187C6F05C7E7C1D366B          国铁久盛（北京）科技有限公司
31  F8A9D63E7999554EB1E0A5D01937FD0F          广西三环企业集团股份有限公司
32  ED03408B6BF9B99466A8B4AC59CF0D6D            北京时代文仪家具有限公司
33  ECF94FF38B94C425D6486259BC979579          北京热景生物技术股份有限公司
34  ECF69232649441106320283475BEC6C6          南京轨道交通系统工程有限公司
35  ECEF4A4299192700EC123539C9D9C937              中泰证券股份有限公司
36  ECE864D244F5D79A55DD4606832EED66            浙江国贸云商控股有限公司
37  ECE677D2E3119C252A785A531BD4CC3B             贵阳鑫恒泰实业有限公司
38  ECE0D96BABD9F7AE169266D41D349557          华域科尔本施密特活塞有限公司
39  ECDDA59FBFE4FE2B48ACFFDB46813C3A              浙江大东鞋业有限公司
40  ECDBDED6B6307BC5E032B0620098E9BB              厦门建发股份有限公司
41  ECDB1F9E6AB4B584E8910C05842DBFC1          上海云同纳米材料科技有限公司
42  ECDA49B20DF3814ED620A5327049E840          北京朗信能源环保科技有限公司
43  ECD974CC7247FAB856AF8C9F93CCE587          淮安市建筑科学研究院有限公司
44  ECD2B8AC544B6AF3C59D31A226BF7F05            厦门卓讯信息技术有限公司
45  ECD268C4716A9288A3BC19C81042AD42          北京金山奇剑数码科技有限公司
46  ECC1DC657484ECFA5F0FEF6992E839E3            新乡拓新药业股份有限公司
47  ECBC2A14C18AD2F35021F74F76DF7D8D            珠海亿邦制药有限责任公司
48  EC97AC3D2A328B0A86566B57E11D70B9              新智数字科技有限公司
49  EC95896B092BF581C113583109611B22            中信出版集团股份有限公司
50  EC8FD83DBBE3035FDFD0FD808101B80D          猎居网络科技（上海）有限公司
51  EC8E5D99F621F845835F78292044AF96            碧全（福建）集团有限公司
52  EC85431AEB00F6793F3D8FFDF566D0F9           深圳市来乐智能股份有限公司
53  EC7EBFCC334835CB3D69832C61646567           吉林省威创机电工程有限公司
54  EC7D73E9606BFC7F88A829ACCA774EB5            重庆平伟光电科技有限公司
55  EC751D65C4ED0DC8DF39DD88ACAA47D3              浙江海云环保有限公司
56  EC6877A888B6461C014FDEA4489FA07B              湖南泰鑫瓷业有限公司
57  EC653F50FB12A313C254AA66889C8165              燕开电气股份有限公司
58  EC5F3FC6AC184C192D52EA3DCBB1B601          安庆永强农业科技股份有限公司
59  EC4E4AE2591CF0BA4E7A5AA38642DEFA          苏州朗科生物技术股份有限公司
60  EC4DC4DA8419F6B764C965AF7C099137          伊春市忠芝大山王酒业有限公司
61  EC42962D8A0721F182C07FF719AF04A6              宁波翌达科技有限公司
62  EC3F82BE494A229EA113F427F2EDDAFE            四川点石能源股份有限公司
63  EC35AE0CB259A6A50BF9DE83E5758582            麦默真空技术无锡有限公司
64  EC322FE674534341BBBFA72DD16BFE12            沈阳昊霖智能装备有限公司
65  EC2C9E5853A52F21D2A710A939058142          江苏云光智慧信息科技有限公司
66  EC1BFE3157FACF2B1AFD88E2CAED2304              长沙中迪包装有限公司
67  EC15CBBFC1C9570DB1E2997FC24EDC90          北京创智信科科技股份有限公司
68  EC13A6A86B9FE67D72EAAC0AA03467E9            兰州佛慈制药股份有限公司
69  EC063F64DB65766F691C2A0A1740B6F9            珠海广信友联科技有限公司
70  E041AF8CD48CC1950E25548831A8B69F            北京力拓飞远科技有限公司
71  E04166FD5B60253F90478F3CDBD88E5E            陕西兴化化学股份有限公司
72  E03AB2FA0E97B3DC56C0F4030C6BCD9B           黑龙江出版传媒股份有限公司
73  E032767F83A8AF92FC14A2002F48D323          江苏国光信息产业股份有限公司
74  E02C1105D14ECCA0223A930BE6BDD09F           中山市华塑塑胶科技有限公司
75  DFE66BAEEAE0F26B7F202659023BD142              益新（中国）有限公司
76  DFE5292FF6F1DAE10E336C7E9A256699            鹤山市威瑟纸制品有限公司
77  DFE2A5079F682C4D907A01252173B6AD        光宝联合（北京）科技股份有限公司
78  DFDEDA0DB265870150AD2BF456318294          东莞市盛联滤清器制造有限公司
79  DFD43E8922D4C56F13E0CBFC5F9AF957           深圳市控汇智能股份有限公司
80  DFC960006A8713F3CC1658EEB8C7EC0C          上海瀚海检测技术股份有限公司
81  DFC5211362299AA75FAC3C5CC6BCE44B       重庆大爱成科技（集团）股份有限公司
82  DFB9980DB4F601B893EF84D7C6104283          瑞因生物科技（广州）有限公司
83  DFB8FEB699E19B5A37111B289A216A8E            天津联博化工股份有限公司
84  DFADE2DFD7AACE4B2FB4D0ACF29760F2          江苏悦华健康养老集团有限公司
85  DFA7434065D875D4E85C36142CA11902          杭州萧宏建设环境集团有限公司
86  DFA5CB7DAEF5494C3F3976B960E7EDAD        深圳市安泰科能源环保股份有限公司
87  DFA09CDCDBCA3CC2CFF0D91C53131E89            淮南国力液压装备有限公司
88  DF930286A8D8A5A85D95B9E2F6FFA4B4            南京纳加软件股份有限公司
89  DF8C7E724813C867F277EB3F4D4E23FB              山东浩宇能源有限公司
90  DF7FD385A845B2841BCD379449BDA5D9            仕昌电子（深圳）有限公司
91  DF76BFD0BFE3D929B724DC2B9F5653BE            河北高科环保集团有限公司
92  DF72C37EA33576178FFF2F1A174ABEA0  济南市市政工程设计研究院（集团）有限责任公司
93  DF69CBC7BBF31200BBEFC179B32B6347             中核陕西铀浓缩有限公司
94  DF5BE38936A5DE6EF9ABE3EEFF1731F0          浙江华邦物联技术股份有限公司
95  DF5BCB283ADC1BEF5342261C8994ADE0          怪兽饮料食品（上海）有限公司
96  DF5B20B7FDFA1891016918B8EB001C66              浙江顶誉食品有限公司
97  DF534E1452FF459712FF3386C9084D42           深圳市威远精密技术有限公司
98  DF4F15817860B09A50DAEB02E58B021F        汤谷科技发展（天津）股份有限公司
99  DF44B9465287F6A7FA214EEFB8CCDC26              洋浦慧谷医药有限公司