In [1]:
import pandas as pd
import numpy as np
from pyecharts.charts import Bar, Grid, Pie, Map, WordCloud
from pyecharts import options as opts

In [2]:
import seaborn as sns
import pandas as pd
import matplotlib.pyplot as plt

## 数据读取

In [4]:
df=pd.read_csv(r'D:\desktop\科创指标\企业评级修正.csv')
df=df.set_index('company_id')
df.head()

,score_20200601,score_20200701,score_20200801,score_20200901,score_20201001,score_20201101,score_20201201,score_20210101,score_20210201,score_20210301,...,score_20211201,score_20220101,score_20220201,score_20220301,score_20220401,score_20220501,score_20220601,score_20220701,score_20220801,score_20220901
company_id,,,,,,,,,,,,,,,,,,,,,
ADDAD08AF443AE7EF1CF23D2A0390819,B,B,B,B,B,B,CCC,CCC,CCC,CC,...,CC,C,C,C,C,C,C,C,C,C
AE74FBF27D8C26BADC6CE2B75C23E417,B,B,B,B,B,B,B,CCC,CCC,CCC,...,CCC,CCC,CCC,CCC,CCC,CCC,CCC,CCC,CCC,CCC
B2B84090A7761DA4632012A6504595E0,C,C,C,C,C,C,C,C,C,C,...,CC,CC,CC,CC,CC,CC,CC,CC,CC,CC
BB32D7C1AC4EBF7D1594DF4D0C2A7F98,C,C,C,C,C,C,C,C,CC,CC,...,CC,CC,CC,CC,CC,CC,CC,CC,CC,CC
D19AAD6C856B44607D974D6376014CB4,BBB,BBB,BBB,BBB,BBB,BBB,BBB,BBB,BBB,BBB,...,BBB,BBB,BBB,BB,BB,BB,BB,BBB,BBB,BB

## 数值替换求差

# AAA
# AA
# A
# BBB
# BB
# B
# CCC
# CC
# C

In [5]:
df_x=df.replace({'AAA':9 , 
                 'AA':8 ,
                 'A':7,
                 'BBB':6,
                 'BB':5 ,
                 'B':4 ,
                 'CCC':3 ,
                 'CC':2 ,
                 'C':1 ,
                 })
df_new=df_x.T-df_x.T.shift(1)
df_new.head()

company_id,ADDAD08AF443AE7EF1CF23D2A0390819,AE74FBF27D8C26BADC6CE2B75C23E417,B2B84090A7761DA4632012A6504595E0,BB32D7C1AC4EBF7D1594DF4D0C2A7F98,D19AAD6C856B44607D974D6376014CB4,D27721D4FE690E8201E48C4BA666E0AC,E38314F43FFE022A23643CC0F4608E56,EF31F77E44E8DACDC692960B3EE95404,F041ECABDAEE8D61402B42B681C0DADD,F3D32E4D069C3C3DB6A65A244801FAC7,...,8E0712DB0DA86656B0FBADA227A09BE1,8FBD3E32C651E7D43EE40BD9A17C8420,8FDAF36632417C22FD83C533517BF704,91EF870AED16207D32C9462508E0C8AF,9278AE84F92134A1D63375BEA4CDA507,9ECAD6F93A32F059F9973EDF2D11E921,A2D50EED60A97DD5B5601F30D674D64B,A7482E96FB03C7C221CCE040ABF39E4E,B1EA926561CAE8A633410444851F17A0,B2314880BBAC6F5E9A548FCA4798736E
score_20200601,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
score_20200701,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,1.0,0.0
score_20200801,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,-1.0,NaN,0.0,0.0,0.0
score_20200901,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,NaN,0.0,0.0,0.0
score_20201001,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0

## 下降|上升次数统计

### 降级企业统计（有过下降：包含波动）

In [6]:
company=df_new.columns.tolist()

In [7]:
def statistic(a,b,c,d,e,f,g,h,name1,name2,name3,name4,name5,name6,name7,name8):
    company1=[]
    company2=[]  
    company3=[] 
    company4=[] 
    company5=[] 
    company6=[] 
    company7=[] 
    company8=[] 
    for i in company:
        company1.append(df_new[i].tolist().count(a))
        company2.append(df_new[i].tolist().count(b))
        company3.append(df_new[i].tolist().count(c))
        company4.append(df_new[i].tolist().count(d))
        company5.append(df_new[i].tolist().count(e))
        company6.append(df_new[i].tolist().count(f))
        company7.append(df_new[i].tolist().count(g))
        company8.append(df_new[i].tolist().count(h))  
    pinji=pd.DataFrame()
    pinji[name1]=company1
    pinji[name2]=company2
    pinji[name3]=company3
    pinji[name4]=company4
    pinji[name5]=company5
    pinji[name6]=company6
    pinji[name7]=company7
    pinji[name8]=company8
    pinji.index=company
    return pinji

In [8]:
pinji_down=statistic(-1,-2,-3,-4,-5,-6,-7,-8,'down_1','down_2','down_3','down_4','down_5','down_6','down_7','down_8')
pinji_down

,down_1,down_2,down_3,down_4,down_5,down_6,down_7,down_8
ADDAD08AF443AE7EF1CF23D2A0390819,3,0,0,0,0,0,0,0
AE74FBF27D8C26BADC6CE2B75C23E417,1,0,0,0,0,0,0,0
B2B84090A7761DA4632012A6504595E0,0,0,0,0,0,0,0,0
BB32D7C1AC4EBF7D1594DF4D0C2A7F98,0,0,0,0,0,0,0,0
D19AAD6C856B44607D974D6376014CB4,2,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...
9ECAD6F93A32F059F9973EDF2D11E921,1,0,0,0,0,0,0,0
A2D50EED60A97DD5B5601F30D674D64B,0,0,0,0,0,0,0,0
A7482E96FB03C7C221CCE040ABF39E4E,0,0,0,0,0,0,0,0
B1EA926561CAE8A633410444851F17A0,1,0,0,0,0,0,0,0
B2314880BBAC6F5E9A548FCA4798736E,1,0,0,0,0,0,0,0

In [16]:
#评级下降一级的企业个数：301876
#评级下降两次,每次降一级的企业个数：102415
#评级下降三次,每次降一级的企业个数：33351
#评级下降四次,每次降一级的企业个数：10946
#评级下降五次,每次降一级的企业个数：3294
#评级下降六次,每次降一级的企业个数：808
#评级下降七次,每次降一级的企业个数：195
#评级下降八次,每次降一级的企业个数：38
#评级下降九次,每次降一级的企业个数：6
#评级下降10次,每次降一级的企业个数：0
print(len(pinji_down[pinji_down['down_1']>5]))
#评级下降两级的企业个数：4031
#评级下降两次,每次降两级的企业个数：7
#评级下降两次,每次降两级的企业个数：0
print(len(pinji_down[pinji_down['down_2']>0]))
#评级下降三级的企业个数：2
#评级下降两次,每次降三级的企业个数：0
print(len(pinji_down[pinji_down['down_3']>0]))
print(len(pinji_down[pinji_down['down_4']>0]))
print(len(pinji_down[pinji_down['down_5']>0]))
print(len(pinji_down[pinji_down['down_6']>0]))
print(len(pinji_down[pinji_down['down_7']>0]))
print(len(pinji_down[pinji_down['down_8']>0]))

15
5157
204
22
6
1
0
0

In [17]:
pinji_down[pinji_down['down_1']>5]

,down_1,down_2,down_3,down_4,down_5,down_6,down_7,down_8
B7D7F4D47B9C99AF6C7087AA9BAEF145,6,0,0,0,0,0,0,0
D5EBD0392AB7FBC9CE66BF4CCA1FCABD,6,0,0,0,0,0,0,0
08C4750FA3D66092B9EFFFDF5193AD0B,6,0,0,0,0,0,0,0
128E14AB6D9B864E5BDC354D9BB98F91,6,0,0,0,0,0,0,0
EC12B447F676BBBB031045C74F7A1225,6,0,0,0,0,0,0,0
AF6E052A77A1F20D1C988B33A5B661C5,6,0,0,0,0,0,0,0
1FB65580E2520500C6FA25C2D858BEAD,6,1,0,0,0,0,0,0
5D294A3E3EEBB4E4FB0B1D73C0AB04EA,6,0,0,0,0,0,0,0
4CE7216953D18616A57F1C836128F171,6,0,0,0,0,0,0,0
1BE64AA7F7C8277201BDC1DBFCE79863,6,0,0,0,0,0,0,0
D2345F40F8CDDC2CAF35EBE1CD6B386A,6,0,0,0,0,0,0,0
18C2EFEDB035D257BDC11C065FBA542B,6,0,0,0,0,0,0,0
BF7A6D26FD21C54B93192FEB67D478B9,6,0,0,0,0,0,0,0
0221E624DFADA45B9DE5F11CFEB9BD4F,6,0,0,0,0,0,0,0
ED2BFC31431F3B8898BC60975CCCA3BA,6,0,0,0,0,0,0,0

### 升级企业统计（有过上升：包含波动）

In [10]:
pinji_up=statistic(1,2,3,4,5,6,7,8,'up_1','up_2','up_3','up_4','up_5','up_6','up_7','up_8')
pinji_up

,up_1,up_2,up_3,up_4,up_5,up_6,up_7,up_8
53B3B1D3ACEC8011CBA90D51CAF4B12C,0,0,0,0,0,0,0,0
5820D16894C5B6218B6FAD279AFAFB10,2,0,0,0,0,0,0,0
602DE87413DE30FC5CD989543B385E9C,0,0,0,0,0,0,0,0
683DAF5667CF2EE48B0A7575965DE401,0,0,0,0,0,0,0,0
6EFF05FE81B1ED0A816A01DB25638BBE,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...
F160B421DFB0A519FA3E8370B3E070FB,0,0,0,0,0,0,0,0
B32D5DFF9D120C1089D02BB4EC60FD5A,0,0,0,0,0,0,0,0
71DCD29882BB8C57F19BD2F35E496821,0,0,0,0,0,0,0,0
13705465131426A08ADE570C7248DE54,0,0,0,0,0,0,0,0
1FA8EF181198C1E6601C00C9FCDC8DC7,0,0,0,0,0,0,0,0

In [11]:
#评级上升一级的企业个数：598458
#评级上升两次,每次升一级的企业个数：231039
#评级上升三次,每次升一级的企业个数：63224
#评级上升四次,每次升一级的企业个数：17822
#评级上升五次,每次升一级的企业个数：5158
#评级上升六次,每次升一级的企业个数：1285
#评级上升七次,每次升一级的企业个数：290
#评级上升八次,每次升一级的企业个数：67
#评级上升九次,每次升一级的企业个数：11
#评级上升十次,每次升一级的企业个数：2
print(len(pinji_up[pinji_up['up_1']>0]))
#评级上升两级的企业个数：26561
#评级上升两次,每次升两级的企业个数：69
#评级上升三次,每次升两级的企业个数：1
#评级上升四次,每次升两级的企业个数：0
print(len(pinji_up[pinji_up['up_2']>0]))
#评级上升三级的企业个数：112
#评级上升两次,每次升三级的企业个数：0
print(len(pinji_up[pinji_up['up_3']>0]))
#评级上升四级的企业个数：2
#评级上升两次,每次升四级的企业个数：0
print(len(pinji_up[pinji_up['up_4']>0]))
#评级上升五级的企业个数：0
#评级上升两次,每次升四级的企业个数：0
print(len(pinji_up[pinji_up['up_5']>0]))
print(len(pinji_up[pinji_up['up_6']>0]))
print(len(pinji_up[pinji_up['up_7']>0]))
print(len(pinji_up[pinji_up['up_8']>0]))

598458
26561
112
2
0
0
0
0

In [12]:
#对应降级|升级企业company_id
pinji_up[pinji_up['up_4']>0]

,up_1,up_2,up_3,up_4,up_5,up_6,up_7,up_8
BCF472D0BDEC8BFDC00ADF63F4402CE0,0,0,0,1,0,0,0,0
BACE53F623374A5551773E170EA4783E,0,0,0,1,0,0,0,0

In [101]:
#对应企业评级
df_x.loc[['5982826E9878FA20E3BD31BEE773B214', '4B3AA96C7813CB22ABA759D680F450B4',
       '0C8BBEE7A1AEE270151290E0C8AD6420', 'BE2FC2DE6DF2D511D02AFC26DBC91BAE'],:]

,score_20200601,score_20200701,score_20200801,score_20200901,score_20201001,score_20201101,score_20201201,score_20210101,score_20210201,score_20210301,...,score_20210901,score_20211001,score_20211101,score_20211201,score_20220101,score_20220201,score_20220301,score_20220401,score_20220501,score_20220601
company_id,,,,,,,,,,,,,,,,,,,,,
5982826E9878FA20E3BD31BEE773B214,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,4.0,4.0,4.0,4.0
4B3AA96C7813CB22ABA759D680F450B4,2.0,5.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,5.0,...,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0
0C8BBEE7A1AEE270151290E0C8AD6420,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0
BE2FC2DE6DF2D511D02AFC26DBC91BAE,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,4.0,...,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0

###  降级企业统计（出现下降，且未出现上升）

In [13]:
pinji_down['down_sum']=pinji_down.sum(axis=1)
pinji_up['up_sum']=pinji_up.sum(axis=1)

In [14]:
df=pd.concat([pinji_up,pinji_down],axis=1)
df

,up_1,up_2,up_3,up_4,up_5,up_6,up_7,up_8,up_sum,down_1,down_2,down_3,down_4,down_5,down_6,down_7,down_8,down_sum
53B3B1D3ACEC8011CBA90D51CAF4B12C,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,2
5820D16894C5B6218B6FAD279AFAFB10,2,0,0,0,0,0,0,0,2,0,0,0,0,0,0,0,0,0
602DE87413DE30FC5CD989543B385E9C,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
683DAF5667CF2EE48B0A7575965DE401,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
6EFF05FE81B1ED0A816A01DB25638BBE,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
F160B421DFB0A519FA3E8370B3E070FB,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
B32D5DFF9D120C1089D02BB4EC60FD5A,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
71DCD29882BB8C57F19BD2F35E496821,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
13705465131426A08ADE570C7248DE54,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1FA8EF181198C1E6601C00C9FCDC8DC7,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [15]:
#月降一级：47318
#评级下降两次,月降一级企业个数：5413
#评级下降三次,月降一级企业个数：192
#评级下降四次,月降一级企业个数：4
#评级下降五次,月降一级企业个数：1
print(len(df[(df['down_1']>0) & (df['up_sum']==0)]))
#月降两级：805
print(len(df[(df['down_2']>0) & (df['up_sum']==0)]))
#月降三级：0
print(len(df[(df['down_3']>0) & (df['up_sum']==0)]))

47318
805
0

In [19]:
df[(df['down_1']>4) & (df['up_sum']==0)].index

Index(['460724AF76583C74F79FF24DFFF8F1FE'], dtype='object')

### 升级企业统计（出现上升，且未出现下降）

In [ ]:
#月升一级：343591
#评级升两次,月升一级企业个数：85595
#评级升三次,月升一级企业个数：7150
#评级升四次,月升一级企业个数：423
#评级升五次,月升一级企业个数：24
#评级升六次,月升一级企业个数：2
print(len(df[(df['up_1']>0) & (df['down_sum']==0)]))
#月升两级：21693
#评级升两次,月升两级企业个数：13
print(len(df[(df['up_2']>0) & (df['down_sum']==0)]))
#月升三级：67
print(len(df[(df['up_3']>0) & (df['down_sum']==0)]))

In [20]:
print(len(df[(df['up_1']>4) & (df['down_sum']==0)]))

24

In [30]:
list(df[(df['up_1']>2) & (df['down_sum']==0)].index)[-300:]

['31E887F1CF83AC8B91BC72FDB2D6D694',
 'BB0029E9EA5E375D87192F8272D72C18',
 '2F5CAA789BF0940C5EB9FFDC75B89162',
 '7E846B117CF42D625089643E719BA2F8',
 'A7D7C085CA591BD70AC3C47A051B6BD8',
 '825230CBE3B443E0ACF6DFF86016384F',
 '2B6B8F34BF910AD6867A1C3C9A5F798D',
 'C6DA8170B2B8224B9B044BDD524AE658',
 '0FFF65436021A8EB5B9A85AC7C108791',
 '9B926581C489216BB44D7D81FC65D893',
 '5DCC6C00D2343F8F4C679B762168A39E',
 '77F4EB4B9025C4861889B2DAD50644A7',
 'A77D2E2E4092090072C75C72FE445FAB',
 'EC3C8BD00CD3CFE6F13EB91996B08A1E',
 '072BFEC0A32FAF857FD396C9DBAF0468',
 '22D46B0F9A2FB72D68535E2424F6BFA9',
 'D86673920768AE8AD6B3892968D98E9D',
 'A719FFF84A23BC5F36598B19CAE140D5',
 '5F3E9E2B445060041FE79624BB8FD32B',
 'B750043556066C3CC22BE656A972ABB3',
 '26147F23AD1E988D3E0CF8A98BB0A04C',
 '2AC8D6045DF2655D3EC961E38696B73D',
 '8865F2D5B1AC16DC61DD2F0CD5A2575F',
 'C3B3FCE3F4AA34BC701B1933F0BD18E8',
 '6494AA82CBBABFA72D0FF219F53BEE36',
 'D7D3B04F4DE692A234D5EB667C58D311',
 'A95C738F809A00C1408E8F878700A0A8',
 '5C06ED3106458D26B9E3985EF8F6B519',
 '7FB1769503572C8FF69222CE162723DF',
 'D87296E61B354A10488CF3A27BC14849',
 '52D10A55B8574061F6822128B5D8AC55',
 '91E97F5D1E89A60A58CF86763034E1DE',
 'FF071E7AE81536BDA8F3E12773587C75',
 '3FAB599259684C36F095A7A01F0A5319',
 'A548FA7A56008A335F82F1E4B72B093B',
 'CEB7F0A4DD2F647D011379635C067503',
 '562140FBC3D74ABD0E686312E7F0AC27',
 'A90F96BACF52E6B309341016DA8033E3',
 'AAC0A1D488501CCAA73D9F12D049A926',
 '887F9904DC245D41ECAD5D17A3A5633A',
 '2DFC56D55FA9548A083D98672380C389',
 '529FC7BE5ED1B7FD2BCB56C75819B7D6',
 '978F4E1B2468CFEE35FDFA1652376B9E',
 '3686BA25CFA2A9185DACAAACE5A12B2C',
 'D715DB266EC208BE8B7AA421E92F33D7',
 '16B994E4C8B869CA9416F9ECD5D769D5',
 'C0A663F4E908B8F6A298EF33DA65ADB8',
 'CF668EC6F12190E79668279696FF295C',
 'D557FF249361B4BC1FA13D973D9D468E',
 'D7ABA2AEDFF94366C822817E4A2FA213',
 'B81A15C4FA697333312AEA475661DACD',
 '0BA81C0C30C9C058F30487D8AD4A9E24',
 'FE9EE0A17C42A1EF8C0DB7916C2FD6DA',
 'C787B96C4FC68100B3A5D96E9470C419',
 '6BB0648D842889E0D422E6006202E5DA',
 '7EA36B6AFB4CC0635E52CA9254974D24',
 'A48E92C02DCAC71BDED295305221107C',
 'FC9E8C591EABFA78C1C82368BC20310A',
 '2BBD6E56B414F564D93FED5BFA0C7144',
 'E5EB4DD4FCD7A3F4ABADCB72D2B5BEAE',
 '9C738D6FE3E61BFC7B315F663F68AD1F',
 'C07BC0C652C60F8D2E2A1E5F4DD85496',
 'EEC3334D1370DA1503E7AB505715DB13',
 'BF77C34533A18FC4B93B9BAB34D79EDA',
 '5228366A30F54C9CA858C43711BAD51E',
 'A7D64E1E2D71F36B2EC5E7A74E8C2066',
 'BD833F580FD4D5D88C455D4842AC54CE',
 '1DA026E937757295816936169A9844AE',
 '4966FBB55EF180060A43475816340A2F',
 '3B33859272A9FDEA1AC4DF3EF2E53026',
 '49EBB5118DB1D1929D8864E92BC72C03',
 'B167B70251A72380F2A1E119A6B68EFD',
 '9A0E212D68ECDC5E4B1544DF3A7C36B6',
 '2370A7534EEFAEF266167FACFC21AB2F',
 'C08EE7C2A8E5AB8DDEB3DDB12F6D577D',
 '46E1F99B9CED8033951DDE3605914462',
 '7B5BE835816A5761266D0557DFE96BFE',
 '316180C9A00FC0D0E7E51820336F4F65',
 'D1DADED8443BD99C5E880E7CD7C60B33',
 '683C78A5EC8DECB953DA6CE27A51370E',
 'FAA9E05D43C36D72A28BBDB78B8C5A65',
 '0AD53847FAB764D11D26EBE8BEBBFA10',
 '55D7385AD0E6A440D6DCDDD8FAFB2D29',
 '98C6A51675DE25707FFABF0A3554A76A',
 'BF119C32276470B97425CE9001C01198',
 '28AFF90BC314417BA0767A0F592D7047',
 '852F09BE2A459CB216F8FE412E69450B',
 '5F1F2482F3B148EC6DA8DA2C22EE5EFF',
 '361C3CF354318248B8E7F2E20F1C1F71',
 '556FAC6EE3F7A8822AA306FEB882E9EF',
 'EAF5C1597CA41239F0435A82185D09C3',
 '9E55850F6E47BA497BDB4ACA0A518B97',
 '50FB4484EB0ADEABDC76456CD1EE7BE1',
 '6FF6B1115398A49A48C659C268ABF91D',
 'E2D76F60453ED07237CFED2797121585',
 '52EF6041623C619A4D7A2593559E14B9',
 '8602262ADBAACBE813D3AFEDB12EB625',
 '0FBCBBA8BCC63E0A8CB44777D5E21472',
 '300B1FBF171803B91C20BC2107A695E7',
 'D7011B14A5E87A2B1DA02574CF1293A1',
 '9BC8EDC8F6FD0BD5E9C85A6A63F01F3B',
 '140F27999F339150C55F594356AFFDDB',
 '0B4D3CA9F22861D57F62EA1D5923B195',
 '76E457CCE01EB50574439A053999A938',
 '7AE31555989AC7DDFFF35F53D186B683',
 '8EF3ADAF566E4F0DA6E4ED12FEABEC6B',
 'CE54F9892482633E2A92144298E5D20A',
 'E65A4669210712C42945E2690734F4B0',
 'D2B5365517D1AD2175E427DF19EC946C',
 '5B14A79AF5C57B0AD05AAFFBAF5058E0',
 '29F6B6C822F1701D32E1204A3826B7EF',
 '2F2D3773E36D02B4BA15ADBE77833F43',
 '78AF2D52AE1DBCE4BA417E0290983D32',
 '520E143B0A7C69B2593D76390232E28A',
 'A56E087A46D17BC30E617BE85DE02050',
 '218C4ACA07385E490DB73AFFA397EAE8',
 '8B50D0AD7D7EAEE236E73F169EB58D2A',
 'C5D27763F9D5971E9C1D8267C8B79896',
 'F1F34ECA1EFEF643E1543EC791BFB306',
 'A65DC54B9047BBF34B3AD72E91BFBC18',
 '25FDD05035E8629568C6D100441A324F',
 '5898C0EF20580A1376F4DD54AE0AEA6E',
 'D72400436121B7C2BD2961C6A7F88DD2',
 '31382BC855DA4220BF1E4E78DA414332',
 '78A1BAF15485ED7AD567763BB537F125',
 '4515D9510D99303B2ACDF98A3D31AA0D',
 '46A26A05AFE30E59A3D611D695E6F81C',
 'D1081AAA02A5C2C327C51712CAA2A844',
 '138ADD134DC006EDA85EAE79A60EC6E7',
 'D0177CE6C246EEBCC75CE48A1FC1E523',
 '1D0C5B9EF94B3ACE60839A3930522611',
 'F235E3B81DCAA62385C4682DAFF54CA2',
 '79BE7F17B2A3E72A33E5B6E78EA35C94',
 '753D2991E4100D933DBEB1C054DB05E5',
 '21CA3E6A40D3625E49D5A55CDE2EEA87',
 '3E36D20649859242AB28F8964F7C2881',
 '0F5B6A56CDBF4E69FA527BE6FD6C1D76',
 '5D116B68CDFC4FD218A5F683BBE44CAE',
 '4A4A4D24464084A3A8AE3E635632D74E',
 'E46B19971EF9E5AA57AD1BD19C3064DC',
 'BC4ED3A22371F24AF5140206C6849B31',
 '21407DECEAC5815955B938CE736812A6',
 '9A958AD5433285098E1D5E049EA1B789',
 '3883C7C23D91677591D04E5F9D33C0F6',
 '0C988DCB6191F027BA830AEB814453F2',
 '9D9622C632A1F9DF9079D05AF71B3DBB',
 '3AE92D087A98CE050EA4CD7E93073E89',
 '8BB3AD79EA675D5F1EB14BE8D7493727',
 'FDBBF28759630799EE51636FA75E807D',
 '3C3771D31F3BBDAB46081DFE4F5D8497',
 '307B89A1340727E00097064229A4CD32',
 '11E1F090FC48123187D84F54EF609FAE',
 'D1750A29718CB09D0DFF8CB0CB78091D',
 'D47722A2CA945023A160B5B75D32EF03',
 '8D908263CDB0E90E44263FE4DE341696',
 'EB7149F2E578E2B7DBA8E5F6FE6764CD',
 '4CF1C957715B9B8D2705F6174BA2FE26',
 '8890E8AF230F7BE762AAF17EFB62303D',
 '42AB11B7510BD95964AD7329B6DAC3BE',
 '251BD04886E38B9CB38132FFD5DDE39D',
 'B5803FA374200B776F7E529FFBB77DA6',
 'DDA87CCE89EDEDAA4F5C0F9C0B39D938',
 'BF825005423CCB414FB7A493BA78F121',
 '807E0DFC8E48450138BC7BDA62E945E3',
 'B5211EE183592EA5B4E213C42DD5B0E2',
 '4BC64C2CCA5CDA79D3C30685C267C8A2',
 '48625C31A0CB88E9966A7ABE6F30855D',
 '1307EE52F2A0B8B8D83953472148E56A',
 'C95E48C2290282CCE6A6694FAF9EC03C',
 '8C681AE0127A5B8BC9D4FFAD97645026',
 'A6FAA962639ED8267604869C27179006',
 '70FEDED242DF599B07231D1B2707B8A8',
 '6E18026C686214D67C5F8AC25EE0A59C',
 '6E55F7006EA7A5B43AE362D97232AE8B',
 '1150923646D5098EE7185AD7A803153B',
 '2919B85A94E7124F3C1A017C607313D4',
 'AEDDD7CA558C9AE49C49BB69E8A09BD2',
 '4583DEDADA1F289E80D4462050E47282',
 '15EC64A92779DC49CD4D3771A261A592',
 '10E6A1F0D08783BE88ED2059E8ECC4A7',
 '24801BE4170DA280F77FC1F942434754',
 '4E999CA6458C9CF51A8BA3ED02A5260D',
 'E87A28CD74E331BEE25C81BD5953293A',
 'FA2B9CE2BBB7D8D81C5F5D6B00E29331',
 '4A7814B9B9D562FBF567D24D3FD2C483',
 '55370A6F63AB83771B9C506DAFB25B82',
 '71E94AB75C0A34A8C1179FDEF0C29C98',
 '0EF6FFB02AEFF73F74450A73746C9019',
 '24E985E09A241E217982A5D18A385ABD',
 'A4997A0B26B66E6F76311087FD94CB86',
 'B3F754CF01B85767D3B9D23447F71E95',
 '2452E86C599691383C50EE8F0A9BD047',
 'C537862509942410C28E795F091B990C',
 '42FDFA4817A15ECDF65CE7BD991F0B4E',
 '70D76438E0B37DCB1E66023A336BFBFF',
 '19FB4CC1092C4AB3B090E66396FDFBC6',
 '413EB4ADFE9B8C601891E77BDB3FCB81',
 '0810D0AF2902D15BA02AED181D4F06CE',
 'F86E04ADD99B7277A4BC022E3134046A',
 '3A49AFCDD718858C375BCBE4EBBF72B3',
 'C0FCBC7CD8E9752BCB2001322C43F260',
 'DDAAB5037F021917D4F724C3B5A662CE',
 '78E187060F8413E57CD635995B35082E',
 '2D31A6C6C83107E7DF23ECC1BA0C8194',
 '23B3548BC67107002256F96D9476EDBE',
 'AFA1D5A72180747CAD60233A6B697B00',
 '474AC99211D0C47F4F54AF465C58B077',
 '5A5EEEA9790FC1BE5AA8C0D22F87A205',
 'BA61AAD040DDC4C17D7138EE5A5B2F63',
 'CAAE07586FAE6B0CAFC7068980FA60A0',
 '4901E695A0EC1FADD93A7127E3BC081D',
 'BE47B7E716380FC0340C51DF2C6D102D',
 '8D174960074F477B9F6DD534BAE14CD9',
 'C519289AFEF1DF00466F9A2FC513BD86',
 '2B624E3AC2619062F588FA84B1BEFA21',
 '7064820BD1652DB775B8DD495E5D0577',
 '0211A9BCCD28025E0D478EB066763ABA',
 'B60CBA92A5BB0C3BD54B6A36E2947B0F',
 '886DC234C7691DD74A03CEE70E7A0A12',
 'E08F34093058B139FEE91D22ABC4AB99',
 'F79F4ABE0431B92C4D4D70346C80F67F',
 '0C2FCF7039DD26F96E00BFDB21AF170C',
 '10D865D1C2C3039874E0E7C8320DA5CC',
 '452A3F94F64BE4EC803C2E693043E142',
 'DEDD68C7B156B2AE97DAA7386CA1E3B3',
 'D7D8784CD7F335B56823DA3A7B8F2CDE',
 '2028B3483B5F7E6E0F3019927D97BC11',
 '73D0083F5F661A8CF9ADF19AAF6F2B59',
 '09BA7D37BC35AF1862BAFD8E8EE4A38F',
 'D11F5ED89F3FA9DFCBD7968CF9494E3E',
 '00E45BDE98A49705405AD6B0D718525B',
 '059F14AB2F7C80843311712EB3625BEB',
 'B87F475A40D8C30F00FFA7BEFBA1F397',
 'ACE48A16CE230C12423ED1A9A02F5BB7',
 'CFDDB7835E359598B61C2C76450C3BF5',
 '4E94A14461FFD1C87BF46AB8E72082E5',
 '46E33CB81748BD591322E0E2F643D1F7',
 '938CFEAFCFC6E8A99643080B6837B1BA',
 'E24F982C2FB0B83C2709DFC8AE6DA4ED',
 '084F3E64D2618B5C59B4A60DF5940155',
 '2F363A1492675882867591E26D129135',
 '1D8C4B572937687B2A6A287E70143013',
 '6809EF45F4158A5405564915547C86B6',
 'BCE7E7AB85FA0136065666DAA2583745',
 'FCD98FA727A54645F6BA793376EF5A07',
 '231786F8627A6C1499859B730A94C1C4',
 '7CE18228DBF07B36C78D19176D70A83B',
 '7C81DC2490F4AA34AEA4DD15EDA0BC83',
 'E0EE111AA8A0F4557592A86D21B954D0',
 'AC064B91724A090C7302E934A25386BA',
 '6513BE307B72E6DA38DBEB0F6644D3B2',
 '4DB7156DDF50220EE8595E3FE9B9331A',
 '59816C65863BA69E4631C92C2990B8AC',
 'E6A35EF918DCA90F01EF6FFAA35B9271',
 '109FB8548F61FB3C889F6AB45F5116AE',
 '253FD38BDF00A7A6A287F72071D9F6F6',
 '79F122C9033938E0D99B8A795D934A94',
 'D569DD8E904C61C6F268EC0631C49D32',
 '4C9483DFA759F4AE3E838EA4EB3EFFB3',
 '0239CACD6C81042F565888840734D841',
 '2B6BDD793C9A10AE24BBE1EF0DAEB07B',
 '9BA53730C08E3C7FA940114D621A9F98',
 'B4A2EDB4E1938FBE2A157291BAC7D5AB',
 '43B896BF6ACA088FF4909849D5DF1B98',
 '491D46C6A36AC919F46FD58CB8CFD3CE',
 'F95A6C7DC891E2982F8BFC83C40F17DF',
 '1F45540DA81FB3D8C7B921D104C54453',
 '70670B1F53918281711AFC9AB1FBE0CA',
 'B49D5D760559F5A0545E8CE0BD03F5EB',
 '7D603819B439526B7B48C36D3B77D73C',
 '904B0F2352AE60F5CE1CCA6970C3E431',
 'C7E506ED3FA31B26D54AF16786D38185',
 '999072A899B2E17AEE22729546DA4979',
 '9961938232C13C54A2E69526B22D9AE0',
 '730CB7D210CBB4F70E9B54465076CEC8',
 '85C8E6CFDCB73840AA486544A20D0EC3',
 '47A667D01009A45636B74789544EE822',
 'AF78E6F38CB19F24AF6C2BD05A150C42',
 'C76B629BB25FDAFD321A50B4CC0413B2',
 '0B43AB7BE5C08529908F6233126EA726',
 '1174FED28B4987A0076A90B407A7BF21',
 'D2ACFBFAF181805BCFD78051E2D346CB',
 'F655DCFB5E7CB9C032A9AD0787570062',
 'E73D7C5EBE1DFDB47364FA7B62D6C43E',
 '9E0915E8F40D4BFFB8E064AB0C60FA86',
 '7A312D1E8831ABD54513AF87A61D8A2A',
 '7768F697D4C7B781170E049CC85CDA81',
 '4B6BF531AFDD32D6541527EFB817D195',
 'D46C8785240E3C1A55051BE3E1F3FBF8',
 '204E2A764F0B543F23BDBC4F4CBF1356',
 '735A2B5F6712154E5CCDFE89B3B87169',
 '522BD09B75AC937784E4213AB07FB1BB',
 '667C3DE9537ADDDFE3364A723727A962',
 '91F30615FA84102726EBF4087AD31BA1',
 '20409B009C2AC343DDAECC746641EE9E',
 '7020F051F3613BE69D51E5D694D2990F',
 '55DF14BFADBB40CB3DB333AB0FF6DBD2',
 '309422A0FC344AEFD1AAB159D22EFF9C',
 '61D7C67947744F4C20EEB345AFFE1409',
 '014F932474DD73D8735F17E2666EAF8A']

In [147]:
df_x.loc[['5982826E9878FA20E3BD31BEE773B214', '0C8BBEE7A1AEE270151290E0C8AD6420',
       'BE2FC2DE6DF2D511D02AFC26DBC91BAE', 'EAFCAAB86776AB9C6596108E506ECE53',
       'BA59CA4BE3BE85115120F49E94F79085', '5F5CF42D7B2B12BB81045F40A7A1B4DB',
       'CCE3CA5F8ED4745A11E18197657E00C5', '540E1A1C4E419527B66DB69B504304C0'],:].to_excel("评级下降九次每次降一级.xlsx")

### 未出现评级变动

In [6]:
df_new_x=df_new.T
df_new_x['count_nan']=df_new_x.apply(lambda x:len(x[np.isnan(x)]),axis=1)
df_new_x['count_0']=df_new_x.apply(lambda x:x.tolist().count(0),axis=1)
# df_new_x[df_new_x['count_nan']==25].to_excel('只有一个评级.xlsx')
df_new_x["sum"]=df_new_x['count_nan']+df_new_x['count_0']
df_new_x[df_new_x['sum']==25].index

,score_20200601,score_20200701,score_20200801,score_20200901,score_20201001,score_20201101,score_20201201,score_20210101,score_20210201,score_20210301,...,score_20210901,score_20211001,score_20211101,score_20211201,score_20220101,score_20220201,score_20220301,score_20220401,score_20220501,score_20220601
company_id,,,,,,,,,,,,,,,,,,,,,
53B3B1D3ACEC8011CBA90D51CAF4B12C,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5820D16894C5B6218B6FAD279AFAFB10,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,1.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
602DE87413DE30FC5CD989543B385E9C,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
683DAF5667CF2EE48B0A7575965DE401,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6EFF05FE81B1ED0A816A01DB25638BBE,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
F160B421DFB0A519FA3E8370B3E070FB,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
B32D5DFF9D120C1089D02BB4EC60FD5A,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
71DCD29882BB8C57F19BD2F35E496821,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13705465131426A08ADE570C7248DE54,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1FA8EF181198C1E6601C00C9FCDC8DC7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [18]:
# df_new_2=df_new.loc[['score_20211201','score_20220101','score_20220201','score_20220301',
#               'score_20220401','score_20220501','score_20220601'],:].T
# df_new_2['count_nan']=df_new_2.apply(lambda x:len(x[np.isnan(x)]),axis=1)
# df_new_2['count_0']=df_new_2.loc[:,['score_20211201','score_20220101','score_20220201','score_20220301',
#               'score_20220401','score_20220501','score_20220601']].apply(lambda x:x.tolist().count(0),axis=1)
# df_new_2['count_0']=df_new_2.loc[:,['score_20211201','score_20220101','score_20220201','score_20220301',
#               'score_20220401','score_20220501','score_20220601']].apply(lambda x:x.tolist().count(0),axis=1)
# len(df_new_2[(df_new_2['sum']==7) & (df_new_2['count_nan']!=0)].index)

In [13]:
# unique=df_new.sum(axis=0).unique().tolist()
# dic={}
# for i in unique:
#     dic[i]=df_new.sum(axis=0).tolist().count(i)
# print(dic)

{-1.0: 70218, 2.0: 114989, 0.0: 437577, 1.0: 333435, 3.0: 10717, -2.0: 8912, 4.0: 771, -3.0: 320, 6.0: 5, -4.0: 5, 5.0: 60, -5.0: 1}